export type CalendarEvent = {
  id: string;
  title: string;
  programmeSlug: string;
  institution: "APIA" | "AFIR" | "MADR" | "MIPE" | "AFM" | "MEAT" | "ADR" | "Ministerul Energiei" | "Comisia Europeană" | "ANCPI";
  date: string;
  eventType: "Lansare" | "Termen Limită" | "Consultare" | "Evaluare" | "Plată Avans" | "Plată Finală";
  county: string;
  status: "Deschis" | "În curând" | "Închis" | "Permanent";
  description: string;
  officialSourceUrl?: string;
};

export const calendarEventsDataset: CalendarEvent[] = [
  // MEAT & Programe Naționale
  {
    id: "cal-meat-1",
    title: "MEAT: Deschidere Modul Depunere Planuri de Afaceri Start-Up Nation 2024–2025",
    programmeSlug: "start-up-nation-2025",
    institution: "MEAT",
    date: "2026-11-01",
    eventType: "Lansare",
    county: "Național",
    status: "În curând",
    description: "Deschiderea oficială a platformei granturi.imm.gov.ro pentru depunerea planurilor de afaceri de către absolvenții cursurilor acreditate PEO.",
    officialSourceUrl: "https://economie.gov.ro/programe-pentru-intreprinderi-mici-si-mijlocii/start-up-nation/",
  },
  {
    id: "cal-meat-2",
    title: "MEAT: Termen Limită Depunere Proiecte Programul Femeia Antreprenor",
    programmeSlug: "meat-femeia-antreprenor",
    institution: "MEAT",
    date: "2026-10-31",
    eventType: "Termen Limită",
    county: "Național",
    status: "În curând",
    description: "Termenul final pentru depunerea electronică a cererilor de finanțare de către IMM-urile cu acționariat feminin majoritar.",
    officialSourceUrl: "https://economie.gov.ro/programe-pentru-intreprinderi-mici-si-mijlocii/femeia-antreprenor/",
  },

  // MIPE / Fonduri Europene 2021-2027
  {
    id: "cal-mipe-1",
    title: "MIPE: Închidere Apel Investiții Productive IMM — Programul Tranziție Justă (PTJ)",
    programmeSlug: "ptj-investitii-productive-imm",
    institution: "MIPE",
    date: "2026-10-31",
    eventType: "Termen Limită",
    county: "Gorj, Hunedoara, Dolj, Galați, Prahova, Mureș",
    status: "Deschis",
    description: "Data limită pentru depunerea proiectelor de investiții productive în valoare de până la 5 milioane EUR în MySMIS2021.",
    officialSourceUrl: "https://mfe.gov.ro/ptj-21-27/",
  },
  {
    id: "cal-mipe-2",
    title: "MIPE: Deschidere Apel Tehnologii Avansate & Inteligență Artificială (PoCIDIF)",
    programmeSlug: "pocidif-tehnologii-avansate-imm",
    institution: "MIPE",
    date: "2026-10-01",
    eventType: "Lansare",
    county: "Național",
    status: "Deschis",
    description: "Lansarea apelului național de proiecte pentru adoptarea soluțiilor AI și Cloud de către IMM-urile din România.",
    officialSourceUrl: "https://mfe.gov.ro/pocidif-21-27/",
  },
  {
    id: "cal-mipe-3",
    title: "MIPE: Termen Limită Depunere Proiecte Dotare Centre Medicale (Programul Sănătate)",
    programmeSlug: "ps-investitii-centre-medicale",
    institution: "MIPE",
    date: "2026-11-15",
    eventType: "Termen Limită",
    county: "Național",
    status: "Deschis",
    description: "Termen limită pentru clinicile și cabinetele medicale private care solicită dotări cu aparatură de înaltă tehnologie.",
    officialSourceUrl: "https://mfe.gov.ro/programul-sanatate-21-27/",
  },

  // Fondul pentru Modernizare & Ministerul Energiei
  {
    id: "cal-energie-1",
    title: "Ministerul Energiei: Termen Limită Apel Autoconsum Întreprinderi (Fondul pentru Modernizare)",
    programmeSlug: "fond-modernizare-autoconsum-intreprinderi",
    institution: "Ministerul Energiei",
    date: "2026-10-31",
    eventType: "Termen Limită",
    county: "Național",
    status: "Deschis",
    description: "Închiderea apelului de 500 milioane EUR pentru instalarea capacităților de producere a energiei solare și eoliene destinate consumului propriu al companiilor.",
    officialSourceUrl: "https://energie.gov.ro/fondul-pentru-modernizare/",
  },

  // Administrația Fondului pentru Mediu (AFM)
  {
    id: "cal-afm-1",
    title: "AFM: Finalizare Înscrieri Programul Casa Verde Fotovoltaice 2024–2026",
    programmeSlug: "afm-casa-verde-fotovoltaice",
    institution: "AFM",
    date: "2026-10-31",
    eventType: "Termen Limită",
    county: "Național",
    status: "Deschis",
    description: "Încheierea sesiunii naționale de rezervare a fondurilor de 30.000 RON pentru panouri și baterii de stocare.",
    officialSourceUrl: "https://www.afm.ro/casa_verde_fotovoltaice.php",
  },
  {
    id: "cal-afm-2",
    title: "AFM: Lansare Înscrieri Fermieri Rabla pentru Tractoare și Mașini Agricole",
    programmeSlug: "afm-rabla-tractoare-agricultura",
    institution: "AFM",
    date: "2026-10-20",
    eventType: "Lansare",
    county: "Național",
    status: "În curând",
    description: "Deschiderea aplicației informatice pentru înscrierea producătorilor agricoli care casează un vehicul vechi și cumpără tractor nou.",
    officialSourceUrl: "https://www.afm.ro/rabla_tractoare.php",
  },

  // Programe Regionale ADR
  {
    id: "cal-adr-1",
    title: "ADR Nord-Vest: Închidere Apel Digitalizare IMM (PR NV 1.1.A)",
    programmeSlug: "adr-nord-vest-digitalizare-si-inovare",
    institution: "ADR",
    date: "2026-10-31",
    eventType: "Termen Limită",
    county: "Bihor, Bistrița-Năsăud, Cluj, Maramureș, Satu Mare, Sălaj",
    status: "Deschis",
    description: "Termenul limită de depunere a cererilor de finanțare de până la 100.000 EUR pentru digitalizarea firmelor din Regiunea Nord-Vest.",
    officialSourceUrl: "https://regionordvest.ro",
  },
  {
    id: "cal-adr-2",
    title: "ADR Vest: Termen Limită Apel Microîntreprinderi (PR Vest 1.3.A)",
    programmeSlug: "adr-vest-microintreprinderi-13a",
    institution: "ADR",
    date: "2026-11-15",
    eventType: "Termen Limită",
    county: "Arad, Caraș-Severin, Hunedoara, Timiș",
    status: "Deschis",
    description: "Închiderea sesiunii de depunere pentru granturi de până la 200.000 EUR în județele Timiș, Arad, Hunedoara și Caraș-Severin.",
    officialSourceUrl: "https://vest.ro",
  },
  {
    id: "cal-adr-3",
    title: "ADR București-Ilfov: Termen Limită Apel Microîntreprinderi Urbane",
    programmeSlug: "adr-bucuresti-ilfov-microintreprinderi",
    institution: "ADR",
    date: "2026-11-15",
    eventType: "Termen Limită",
    county: "București, Ilfov",
    status: "Deschis",
    description: "Data limită pentru depunerea cererilor de finanțare pentru dotări tehnologice în București și județul Ilfov.",
    officialSourceUrl: "https://www.adrbi.ro",
  },
  {
    id: "cal-adr-4",
    title: "ADR Centru: Termen Limită Creșterea Competitivității Microîntreprinderilor (PR Centru 1.4)",
    programmeSlug: "adr-centru-microintreprinderi-turism-servicii",
    institution: "ADR",
    date: "2026-10-31",
    eventType: "Termen Limită",
    county: "Alba, Brașov, Covasna, Harghita, Mureș, Sibiu",
    status: "Deschis",
    description: "Închiderea apelului de proiecte pentru microîntreprinderi în Regiunea Centru.",
    officialSourceUrl: "https://www.regiocentru.ro",
  },

  // Programe Directe UE
  {
    id: "cal-ue-1",
    title: "Comisia Europeană: Termen Cut-Off Full Proposal — EIC Accelerator",
    programmeSlug: "eic-accelerator-deep-tech-europe",
    institution: "Comisia Europeană",
    date: "2026-10-15",
    eventType: "Termen Limită",
    county: "Național",
    status: "Deschis",
    description: "Termenul limită oficial pentru depunerea propunerilor complete de finanțare mixtă (grant până la 2,5 mil EUR + equity 15 mil EUR).",
    officialSourceUrl: "https://eic.ec.europa.eu",
  },

  // AFIR & PAC 2023-2027
  {
    id: "cal-afir-1",
    title: "AFIR: Termen Limită Depunere Proiecte Tineri Fermieri DR-30 (70.000 EUR)",
    programmeSlug: "afir-dr-30-instalare-tineri-fermieri",
    institution: "AFIR",
    date: "2026-10-31",
    eventType: "Termen Limită",
    county: "Național",
    status: "Deschis",
    description: "Închiderea sesiunii oficiale de depunere a cererilor de finanțare pentru instalarea tinerilor fermieri.",
    officialSourceUrl: "https://www.afir.ro",
  },
  {
    id: "cal-afir-2",
    title: "AFIR: Termen Limită Depunere Proiecte Irigații DR-25 (OUAI)",
    programmeSlug: "afir-dr-25-modernizare-irigatii-ouai",
    institution: "AFIR",
    date: "2026-10-31",
    eventType: "Termen Limită",
    county: "Național",
    status: "Deschis",
    description: "Termenul limită pentru depunerea proiectelor de reabilitare a infrastructurii secundare de irigații de către OUAI-uri.",
    officialSourceUrl: "https://www.afir.ro",
  },
  {
    id: "cal-afir-3",
    title: "AFIR: Termen Limită Depunere Proiecte Zootehnie DR-20 (până la 2 mil EUR)",
    programmeSlug: "afir-dr-20-investitii-sector-zootehnic",
    institution: "AFIR",
    date: "2026-11-15",
    eventType: "Termen Limită",
    county: "Național",
    status: "Deschis",
    description: "Termenul final pentru depunerea proiectelor de construire și modernizare ferme de bovine, ovine și păsări.",
    officialSourceUrl: "https://www.afir.ro",
  },

  // APIA & Plăți Directe
  {
    id: "cal-apia-1",
    title: "APIA: Demarare Campanie Plăți în Avans (70% FEGA / 85% FEADR)",
    programmeSlug: "apia-biss-pd-01",
    institution: "APIA",
    date: "2026-10-16",
    eventType: "Plată Avans",
    county: "Național",
    status: "În curând",
    description: "Debursarea tranșelor de avans către fermierii eligibili fără neconformități la controalele administrative și teledetecție.",
    officialSourceUrl: "https://apia.org.ro",
  },
  {
    id: "cal-apia-2",
    title: "APIA: Încheierea Perioadei de Retenție pentru Bovine (SCZ PD-21 / PD-22)",
    programmeSlug: "apia-sprijin-cuplat-vaci-lapte-pd-21",
    institution: "APIA",
    date: "2026-10-15",
    eventType: "Evaluare",
    county: "Național",
    status: "În curând",
    description: "Finalizarea perioadei de 4 luni de retenție obligatorie a efectivelor de vaci de lapte și taurine de carne în exploatație.",
    officialSourceUrl: "https://apia.org.ro",
  },
  {
    id: "cal-apia-3",
    title: "APIA: Demarare Plăți Finale (Sold Regularizare Subvenții)",
    programmeSlug: "apia-biss-pd-01",
    institution: "APIA",
    date: "2026-12-02",
    eventType: "Plată Finală",
    county: "Național",
    status: "În curând",
    description: "Efectuarea plăților finale (diferența de 30% FEGA) pentru fermierii care au primit avansul în luna octombrie.",
    officialSourceUrl: "https://apia.org.ro",
  },
];
