export type CalendarEvent = {
  id: string;
  title: string;
  programmeSlug: string;
  institution: "APIA" | "AFIR" | "MADR" | "MIPE" | "AFM" | "MEAT" | "ADR" | "ANCPI";
  date: string;
  eventType: "Lansare" | "Termen Limită" | "Consultare" | "Evaluare" | "Plată Avans" | "Plată Finală";
  county: string;
  status: "Deschis" | "În curând" | "Închis" | "Permanent";
  description: string;
  officialSourceUrl?: string;
};

export const calendarEventsDataset: CalendarEvent[] = [
  {
    id: "cal-apia-1",
    title: "APIA: Termen Limită Depunere Cerere Unică de Plată fără Penalități",
    programmeSlug: "apia-biss-pd-01",
    institution: "APIA",
    date: "2026-05-15",
    eventType: "Termen Limită",
    county: "Național",
    status: "Închis",
    description: "Termenul limită legal până la care fermierii pot transmite cererea de plată în aplicația IPA Online fără aplicarea reducerilor de 1%/zi de întârziere.",
    officialSourceUrl: "https://apia.org.ro",
  },
  {
    id: "cal-apia-2",
    title: "APIA: Termen Final Depunere Cereri cu Penalități de Întârziere",
    programmeSlug: "apia-biss-pd-01",
    institution: "APIA",
    date: "2026-06-15",
    eventType: "Termen Limită",
    county: "Național",
    status: "Închis",
    description: "Data limită absolută după care cererile unice de plată nu mai sunt acceptate în sistemul informatic IACS.",
    officialSourceUrl: "https://apia.org.ro",
  },
  {
    id: "cal-apia-3",
    title: "APIA: Demarare Campanie Plăți în Avans (70% FEGA / 85% FEADR)",
    programmeSlug: "apia-biss-pd-01",
    institution: "APIA",
    date: "2026-10-16",
    eventType: "Plată Avans",
    county: "Național",
    status: "În curând",
    description: "Debursarea tranșelor de avans către fermierii eligibili fără neconformități la controalele administrative și teledetecție.",
    officialSourceUrl: "https://apia.org.ro",
  },
  {
    id: "cal-apia-4",
    title: "APIA: Încheierea Perioadei de Retenție pentru Bovine (SCZ PD-21 / PD-22)",
    programmeSlug: "apia-sprijin-cuplat-vaci-lapte-pd-21",
    institution: "APIA",
    date: "2026-10-15",
    eventType: "Evaluare",
    county: "Național",
    status: "În curând",
    description: "Finalizarea perioadei de 4 luni de retenție obligatorie a efectivelor de vaci de lapte și taurine de carne în exploatație.",
    officialSourceUrl: "https://apia.org.ro",
  },
  {
    id: "cal-afir-1",
    title: "AFIR: Termen Limită Depunere Proiecte Irigații DR-25 (OUAI)",
    programmeSlug: "afir-dr-25-modernizare-irigatii-ouai",
    institution: "AFIR",
    date: "2026-09-30",
    eventType: "Termen Limită",
    county: "Național",
    status: "Deschis",
    description: "Sesiunea de depunere a proiectelor de reabilitare a infrastructurii secundare de irigații (100% nerambursabil).",
    officialSourceUrl: "https://www.afir.ro",
  },
  {
    id: "cal-afir-2",
    title: "AFIR: Deschidere Sesiune Depunere Tineri Fermieri DR-30 (70.000 EUR)",
    programmeSlug: "afir-dr-30-instalare-tineri-fermieri",
    institution: "AFIR",
    date: "2026-10-01",
    eventType: "Lansare",
    county: "Național",
    status: "În curând",
    description: "Lansarea apelului național pentru instalarea tinerilor fermieri sub 40 de ani în mediul rural.",
    officialSourceUrl: "https://www.afir.ro",
  },
  {
    id: "cal-afir-3",
    title: "AFIR: Termen Limită Depunere DR-14 — Ferme de Mici Dimensiuni (50.000 EUR)",
    programmeSlug: "afir-dr-14-investitii-ferme-de-familie",
    institution: "AFIR",
    date: "2026-10-31",
    eventType: "Termen Limită",
    county: "Național",
    status: "Deschis",
    description: "Închiderea sesiunii de depunere a proiectelor pentru fermele de mici dimensiuni (grant max. 50.000 EUR, 85% sprijin nerambursabil) pe portalul AFIR.",
    officialSourceUrl: "https://www.afir.ro/domenii-de-interventie/detalii-si-anexe-dr-14",
  },
  {
    id: "cal-madr-1",
    title: "MADR: Depunere Cereri Trimestriale Subvenție Motorină (Trimestrul III)",
    programmeSlug: "madr-ajutor-stat-motorina-agricultura",
    institution: "MADR",
    date: "2026-10-31",
    eventType: "Termen Limită",
    county: "Național",
    status: "În curând",
    description: "Depunerea la Centrele Județene APIA a cererilor de restituire a accizei pentru motorina consumată în lunile iulie–septembrie.",
    officialSourceUrl: "https://madr.ro",
  },
  {
    id: "cal-madr-2",
    title: "MADR: Depunere Cereri de Acord Prealabil Subvenție Motorină Anul Următor",
    programmeSlug: "madr-ajutor-stat-motorina-agricultura",
    institution: "MADR",
    date: "2026-12-31",
    eventType: "Termen Limită",
    county: "Național",
    status: "În curând",
    description: "Depunerea dosarelor pentru obținerea acordului prealabil de finanțare a motorinei agricole.",
    officialSourceUrl: "https://madr.ro",
  },
  {
    id: "cal-afm-1",
    title: "AFM: Sesiune de Înscriere Programul Rabla pentru Tractoare",
    programmeSlug: "afm-rabla-tractoare-agricultura",
    institution: "AFM",
    date: "2026-10-15",
    eventType: "Lansare",
    county: "Național",
    status: "În curând",
    description: "Înscrierea fermierilor prin distribuitorii validați pentru granturi de până la 20.000 EUR la casarea unui utilaj vechi.",
    officialSourceUrl: "https://www.afm.ro",
  },
  {
    id: "cal-meat-1",
    title: "MEAT: Start-Up Nation Pilonul II — Depunere Planuri de Afaceri",
    programmeSlug: "start-up-nation-2025",
    institution: "MEAT",
    date: "2026-10-15",
    eventType: "Termen Limită",
    county: "Național",
    status: "Deschis",
    description: "Depunerea online a proiectelor de grant de până la 250.000 RON pe platforma oficială MEAT.",
    officialSourceUrl: "https://economie.gov.ro",
  },
  {
    id: "cal-adr-1",
    title: "ADR Centru: Termen Limită Apel Microîntreprinderi & Turism",
    programmeSlug: "adr-centru-microintreprinderi-turism-servicii",
    institution: "ADR",
    date: "2026-10-31",
    eventType: "Termen Limită",
    county: "Brașov",
    status: "Deschis",
    description: "Închiderea apelului regional pentru dotarea structurilor de cazare și servicii din județele Alba, Brașov, Covasna, Harghita, Mureș și Sibiu.",
    officialSourceUrl: "https://www.regio-adrcentru.ro",
  },
];
