export type CountyIntelligenceProfile = {
  code: string;
  name: string;
  region: string;
  capital: string;
  population: string;
  activeImmCount: string;
  adrName: string;
  apiaCenter: string;
  ojfirCenter: string;
  agriculturalSurfaceHa: string;
  topCrops: string[];
  topLivestock: string[];
  topIndustries: string[];
  keyIncentives: string[];
  ancpiMonthlyAvg: string;
  localFaqs: { question: string; answer: string }[];
};

export const countyProfilesCatalog: Record<string, CountyIntelligenceProfile> = {
  alba: {
    code: "AB",
    name: "Alba",
    region: "Centru",
    capital: "Alba Iulia",
    population: "325.000",
    activeImmCount: "14.200",
    adrName: "ADR Centru",
    apiaCenter: "Centrul Județean APIA Alba — Str. Moților nr. 112, Alba Iulia",
    ojfirCenter: "OJFIR Alba — Str. Primăverii nr. 14, Alba Iulia",
    agriculturalSurfaceHa: "336.000 ha (150.000 ha arabil, 186.000 ha pășuni/fânețe)",
    topCrops: ["Grâu și secară", "Porumb", "Plantații viticole (Podgoria Târnave/Aiud)", "Cartof de sămânță"],
    topLivestock: ["Bovine lapte/carne (rase Bălțată Românească)", "Ovine Țurcană", "Apicultură"],
    topIndustries: ["Industrie Alimentară & Lactate (Albalact)", "Viticultură & Vinificație (Jidvei)", "Prelucrarea Lemnului", "Piese Auto"],
    keyIncentives: [
      "Plăți compensatorii pentru zone montane cu constrângeri naturale (Munții Apuseni).",
      "Sprijin cuplat zootehnic pentru bovine de lapte și carne în zone defavorizate.",
      "Granturi AFIR DR-16 pentru reconversie viticolă în Podgoria Târnavelor.",
      "Linii de finanțare ADR Centru pentru microîntreprinderi de procesare agroalimentară.",
    ],
    ancpiMonthlyAvg: "1.120 tranzacții",
    localFaqs: [
      { question: "Unde se depun cererile APIA în județul Alba?", answer: "La Centrul Județean APIA Alba Iulia sau la centrele locale din Aiud, Blaj, Sebeș, Câmpeni și Cugir." },
      { question: "Există sprijin majorat pentru fermierii din Munții Apuseni?", answer: "Da, fermierii din zona montană defavorizată a județului Alba beneficiază de plăți compensatorii ANC ZM și praguri reduse de animale la sprijinul cuplat." },
    ],
  },
  arad: {
    code: "AR",
    name: "Arad",
    region: "Vest",
    capital: "Arad",
    population: "410.000",
    activeImmCount: "22.500",
    adrName: "ADR Vest",
    apiaCenter: "Centrul Județean APIA Arad — Str. Cloșca nr. 6, Arad",
    ojfirCenter: "OJFIR Arad — Bulevardul Dragalina nr. 2, Arad",
    agriculturalSurfaceHa: "510.000 ha (350.000 ha arabil de înaltă fertilitate)",
    topCrops: ["Grâu", "Porumb boabe", "Floarea-soarelui", "Soia", "Plantații viticole (Podgoria Miniș-Măderat)"],
    topLivestock: ["Porcine", "Bovine de carne", "Avicultură", "Ovine"],
    topIndustries: ["Automotive & Componente", "Industrie Alimentară & Morărit", "Agro-logistică transfrontalieră", "Construcții de vagoane"],
    keyIncentives: [
      "Granturi AFIR DR-15 și DR-22 pentru capacități mari de stocare în silozuri și procesare cereale.",
      "Fonduri pentru modernizarea sistemelor de irigații din Câmpia Aradului.",
      "Sprijin cuplat pentru soia și culturi proteice vegetale.",
      "Incentive pentru parcuri industriale și facilități de export agricol.",
    ],
    ancpiMonthlyAvg: "1.890 tranzacții",
    localFaqs: [
      { question: "Care sunt principalele oportunități de finanțare în Arad?", answer: "Cerealele de câmp, fermele intensive de porcine/bovine și cramele din Podgoria Miniș." },
    ],
  },
  arges: {
    code: "AG",
    name: "Argeș",
    region: "Sud-Muntenia",
    capital: "Pitești",
    population: "570.000",
    activeImmCount: "26.800",
    adrName: "ADR Sud-Muntenia",
    apiaCenter: "Centrul Județean APIA Argeș — Str. Armand Călinescu nr. 44, Pitești",
    ojfirCenter: "OJFIR Argeș — Bulevardul Republicii nr. 148, Pitești",
    agriculturalSurfaceHa: "345.000 ha (180.000 ha arabil, 110.000 ha pășuni montane, 55.000 ha livezi)",
    topCrops: ["Livezi de pruni și meri (Bazinul Topoloveni/Voinești)", "Porumb", "Grâu", "Legumicultură"],
    topLivestock: ["Ovine (Bazinul Muscel/Rucăr)", "Bovine lapte", "Păsări de curte", "Apicultură"],
    topIndustries: ["Automotive (Dacia Renault)", "Procesare Fructe (Magiun de Topoloveni)", "Lactate", "Construcții"],
    keyIncentives: [
      "Sprijin specific AFIR DR-16 pentru pomicultură și depozite frigorifice de fructe.",
      "Plăți de agro-mediu pentru pajiștile alpine din Masivul Făgăraș.",
      "Granturi ADR Sud-Muntenia pentru procesarea produselor tradiționale și ecologice.",
    ],
    ancpiMonthlyAvg: "1.780 tranzacții",
    localFaqs: [
      { question: "Unde se află centrele locale APIA în Argeș?", answer: "La Pitești, Câmpulung Muscel, Curtea de Argeș, Costești și Topoloveni." },
    ],
  },
  bacau: {
    code: "BC",
    name: "Bacău",
    region: "Nord-Est",
    capital: "Bacău",
    population: "590.000",
    activeImmCount: "21.000",
    adrName: "ADR Nord-Est",
    apiaCenter: "Centrul Județean APIA Bacău — Str. George Bacovia nr. 20, Bacău",
    ojfirCenter: "OJFIR Bacău — Str. Vasile Alecsandri nr. 63, Bacău",
    agriculturalSurfaceHa: "320.000 ha (185.000 ha arabil, 120.000 ha fânețe/pășuni)",
    topCrops: ["Porumb", "Grâu", "Floarea-soarelui", "Sfeclă de zahăr", "Pomi fructiferi"],
    topLivestock: ["Avicultură (Pui de carne)", "Bovine de lapte", "Ovine", "Apicultură"],
    topIndustries: ["Industrie Aeronautică", "Agroalimentară (Agricola Bacău)", "Chimie & Îngrășăminte", "Prelucrare Lemn"],
    keyIncentives: [
      "Granturi majore pentru avicultură și procesare carne de pasăre.",
      "Plăți pentru tineri fermieri prin DR-30 în comunele rurale ale județului.",
      "Ajutoare de stat pentru compensarea secetei pe valea Siretului.",
    ],
    ancpiMonthlyAvg: "1.450 tranzacții",
    localFaqs: [
      { question: "Ce măsuri de bunăstare a animalelor sunt active în Bacău?", answer: "Intervențiile APIA pentru bunăstarea păsărilor și a bovinelor de lapte." },
    ],
  },
  bihor: {
    code: "BH",
    name: "Bihor",
    region: "Nord-Vest",
    capital: "Oradea",
    population: "570.000",
    activeImmCount: "29.000",
    adrName: "ADR Nord-Vest",
    apiaCenter: "Centrul Județean APIA Bihor — Str. Dimitrie Cantemir nr. 24-26, Oradea",
    ojfirCenter: "OJFIR Bihor — Str. Moscovei nr. 8, Oradea",
    agriculturalSurfaceHa: "490.000 ha (305.000 ha arabil, 160.000 ha pășuni)",
    topCrops: ["Porumb", "Grâu de toamnă", "Floarea-soarelui", "Rapiță", "Legume în solarii (Bazinul Biharia/Diosig)"],
    topLivestock: ["Porcine", "Bovine Bălțată cu Negru Românească", "Păsări", "Ovine"],
    topIndustries: ["Producție Industrială", "Termalism & Turism", "Logistică Transfrontalieră", "Procesare Carne & Mezeluri"],
    keyIncentives: [
      "Parcuri industriale Eurobusiness Oradea cu facilități fiscale locale.",
      "Granturi de digitalizare și inovare ADR Nord-Vest.",
      "Sprijin cuplat pentru legume cultivate în solarii și sere geotermale.",
    ],
    ancpiMonthlyAvg: "1.920 tranzacții",
    localFaqs: [
      { question: "Se pot folosi apele geotermale la încălzirea serelor din Bihor?", answer: "Da, există măsuri de finanțare AFIR și AFM pentru utilizarea energiei geotermale în serele de legume." },
    ],
  },
  "bistrita-nasaud": {
    code: "BN",
    name: "Bistrița-Năsăud",
    region: "Nord-Vest",
    capital: "Bistrița",
    population: "285.000",
    activeImmCount: "11.800",
    adrName: "ADR Nord-Vest",
    apiaCenter: "Centrul Județean APIA Bistrița-Năsăud — Str. Calea Moldovei nr. 17, Bistrița",
    ojfirCenter: "OJFIR Bistrița-Năsăud — Str. 1 Decembrie nr. 30, Bistrița",
    agriculturalSurfaceHa: "298.000 ha (predominant pășuni și fânețe naturale 190.000 ha, 95.000 ha arabil)",
    topCrops: ["Pomi fructiferi (Bazinul Pomicol Bistrița)", "Cartof", "Cereale furajere", "Plantații de viță-de-vie (Lechința)"],
    topLivestock: ["Bovine pentru lapte (rase de munte)", "Ovine Țurcană", "Apicultură ecologică"],
    topIndustries: ["Prelucrare Mase Plastice & Cablaje", "Lactate Tradiționale", "Pomicultură & Sucuri Naturale", "Turism Balnear (Sângeorz-Băi)"],
    keyIncentives: [
      "Subvenții majorate pentru agricultură ecologică și zone montane ANC ZM.",
      "Granturi pentru livezi moderne superintensive de meri și pruni prin DR-16.",
      "Sprijin pentru centre locale de colectare și procesare lapte.",
    ],
    ancpiMonthlyAvg: "920 tranzacții",
    localFaqs: [
      { question: "Unde sunt centrele locale APIA în Bistrița-Năsăud?", answer: "Bistrița, Beclean, Năsăud, Sângeorz-Băi și Teaca." },
    ],
  },
  botosani: {
    code: "BT",
    name: "Botoșani",
    region: "Nord-Est",
    capital: "Botoșani",
    population: "395.000",
    activeImmCount: "12.400",
    adrName: "ADR Nord-Est",
    apiaCenter: "Centrul Județean APIA Botoșani — Str. I.C. Brătianu nr. 53, Botoșani",
    ojfirCenter: "OJFIR Botoșani — Str. Cuza Vodă nr. 2, Botoșani",
    agriculturalSurfaceHa: "385.000 ha (290.000 ha arabil de mare fertilitate, cernoziomuri)",
    topCrops: ["Grâu", "Porumb", "Floarea-soarelui", "Soia", "Sfeclă de zahăr"],
    topLivestock: ["Ovine din rasa Karakul de Botoșani (pielicele)", "Bovine de lapte", "Piscicultură (iazuri și acumulări)"],
    topIndustries: ["Confectii Textile", "Industrie Alimentară & Morărit", "Lactate", "Piscicultură"],
    keyIncentives: [
      "Sprijin cuplat zootehnic pentru oile din rasa Karakul de Botoșani.",
      "Programe de reabilitare a infrastructurii secundare de irigații pe râul Prut (DR-25).",
      "Ajutoare pentru tineri fermieri prin DR-30.",
    ],
    ancpiMonthlyAvg: "1.050 tranzacții",
    localFaqs: [
      { question: "Este eligibilă rasa Karakul de Botoșani la sprijin cuplat?", answer: "Da, Karakul de Botoșani este rasă autohtonă eligibilă prioritar la sprijinul cuplat PD-24 și pachetele de rase pe cale de dispariție." },
    ],
  },
  brasov: {
    code: "BV",
    name: "Brașov",
    region: "Centru",
    capital: "Brașov",
    population: "550.000",
    activeImmCount: "31.000",
    adrName: "ADR Centru",
    apiaCenter: "Centrul Județean APIA Brașov — Str. Fanionului nr. 25, Brașov",
    ojfirCenter: "OJFIR Brașov — Str. Mihail Kogălniceanu nr. 13, Brașov",
    agriculturalSurfaceHa: "295.000 ha (120.000 ha arabil, 170.000 ha pășuni montane / Țara Bârsei)",
    topCrops: ["Cartof de consum și sămânță (Institutul Cartofului Brașov)", "Sfeclă de zahăr", "Triticale", "Fânețe alpine"],
    topLivestock: ["Bovine lapte (Bălțată Românească)", "Ovine (Bazinul Bran-Moieciu)", "Piscicultură montană"],
    topIndustries: ["Aeronautică & Producție", "Turism & HoReCa", "Industrie Alimentară & Lactate (Olympus)", "Energie regenerabilă"],
    keyIncentives: [
      "Sprijin cuplat pentru cartoful de sămânță și cartoful timpuriu.",
      "Finanțări speciale ADR Centru pentru facilități turistice și agroturism montan.",
      "Granturi pentru silozuri și depozite climatizate de cartofi.",
    ],
    ancpiMonthlyAvg: "2.480 tranzacții",
    localFaqs: [
      { question: "Ce subvenții se acordă pentru cartofi în Brașov?", answer: "Sprijinul cuplat vegetal PD-14 pentru cartof de sămânță și ajutorul de minimis pentru cartof de consum." },
    ],
  },
  braila: {
    code: "BR",
    name: "Brăila",
    region: "Sud-Est",
    capital: "Brăila",
    population: "280.000",
    activeImmCount: "11.500",
    adrName: "ADR Sud-Est",
    apiaCenter: "Centrul Județean APIA Brăila — Calea Călărașilor nr. 54, Brăila",
    ojfirCenter: "OJFIR Brăila — Bulevardul Independenței nr. 21, Brăila",
    agriculturalSurfaceHa: "390.000 ha (350.000 ha arabil fertil, Insula Mare a Brăilei)",
    topCrops: ["Grâu", "Porumb", "Orz", "Floarea-soarelui", "Lucernă", "Soia"],
    topLivestock: ["Ovine de carne", "Porcine în complexe industriale", "Piscicultură (Balta Brăilei)"],
    topIndustries: ["Construcții Navale", "Industrie Morărit & Panificație", "Agro-logistică fluvială & portuară"],
    keyIncentives: [
      "Fonduri masive pentru reabilitarea marilor sisteme de irigații (ANIF / DR-25).",
      "Granturi AFIR pentru capacități mari de depozitare în silozuri portuare.",
      "Sprijin cuplat pentru culturile de soia și lucernă.",
    ],
    ancpiMonthlyAvg: "1.180 tranzacții",
    localFaqs: [
      { question: "Cum se accesează fondurile pentru irigații în Brăila?", answer: "Prin Organizațiile de Utilizatori de Apă (OUAI) înscrise pe măsura DR-25 cu finanțare nerambursabilă de 100%." },
    ],
  },
  bucuresti: {
    code: "B",
    name: "București",
    region: "București-Ilfov",
    capital: "Municipiul București",
    population: "2.100.000",
    activeImmCount: "145.000",
    adrName: "ADR București-Ilfov",
    apiaCenter: "Centrul APIA București-Ilfov — Bulevardul Carol I nr. 12, București",
    ojfirCenter: "OJFIR Ilfov-București — Str. Știrbei Vodă nr. 43, București",
    agriculturalSurfaceHa: "1.200 ha (spații experimentale, sere urbane, pepiniere)",
    topCrops: ["Horticultură urbană", "Floricultură", "Cercetare agronomică (USAMV)"],
    topLivestock: ["Cercetare veterinară și animale de companie"],
    topIndustries: ["IT & Software", "Servicii Financiare & Consultanță", "Comerț & Distribuție", "Construcții"],
    keyIncentives: [
      "Axa PNRR pentru digitalizarea IMM-urilor și tranziția verde.",
      "Programul Start-Up Nation Pilonul I și II.",
      "Punctaj maxim la granturile de inovare și tehnologii emergente prin ADR BI.",
    ],
    ancpiMonthlyAvg: "8.912 tranzacții",
    localFaqs: [
      { question: "Pot firmele din București depune proiecte pe fonduri agricole?", answer: "Da, firmele cu sediul în București pot aplica dacă punctul de lucru și exploatația agricolă sunt situate în mediul rural eligibil." },
    ],
  },
  buzau: {
    code: "BZ",
    name: "Buzău",
    region: "Sud-Est",
    capital: "Buzău",
    population: "405.000",
    activeImmCount: "15.600",
    adrName: "ADR Sud-Est",
    apiaCenter: "Centrul Județean APIA Buzău — Str. Victoriei nr. 1, Buzău",
    ojfirCenter: "OJFIR Buzău — Str. Unirii nr. 10, Buzău",
    agriculturalSurfaceHa: "400.000 ha (260.000 ha arabil, 90.000 ha pășuni, 30.000 ha livezi/vii)",
    topCrops: ["Legumicultură (Banca de Resurse Genetice Vegetale Buzău / Câmpia Buzăului)", "Viță-de-vie (Dealul Mare - Pietroasele)", "Grâu", "Floarea-soarelui"],
    topLivestock: ["Ovine", "Bovine carne", "Apicultură"],
    topIndustries: ["Prelucrare Metalurgică", "Industrie Alimentară & Vinuri DOC Pietroasa", "Legumicultură & Conserve"],
    keyIncentives: [
      "Subvenții specifice pentru legumicultură în spații protejate (Programul Tomata).",
      "Fonduri de reconversie viticolă în faimosul areal Dealul Mare.",
      "Granturi pentru înființarea de depozite climatizate de legume.",
    ],
    ancpiMonthlyAvg: "1.340 tranzacții",
    localFaqs: [
      { question: "Ce oportunități există pentru legumicultorii din Buzău?", answer: "Sprijinul cuplat PD-12/PD-13 pentru legume în câmp și sere, plus Programul Tomata derulat prin DAJ Buzău." },
    ],
  },
  calarasi: {
    code: "CL",
    name: "Călărași",
    region: "Sud-Muntenia",
    capital: "Călărași",
    population: "285.000",
    activeImmCount: "10.800",
    adrName: "ADR Sud-Muntenia",
    apiaCenter: "Centrul Județean APIA Călărași — Str. Progresul nr. 23, Călărași",
    ojfirCenter: "OJFIR Călărași — Str. București nr. 140, Călărași",
    agriculturalSurfaceHa: "425.000 ha (peste 390.000 ha teren arabil de calitate excepțională Clasa I)",
    topCrops: ["Grâu", "Porumb", "Rapiță", "Floarea-soarelui", "Orz", "Soia"],
    topLivestock: ["Avicultură de mare capacitate", "Porcine", "Bovine carne"],
    topIndustries: ["Comerț & Silozuri Fluviale (Dunăre)", "Industrie Alimentară & Morărit", "Prefabricate & Metalurgie"],
    keyIncentives: [
      "Granturi pentru baze de recepție și silozuri portuare la Dunăre.",
      "Proiecte majore de irigații OUAI prin intervenția DR-25.",
      "Eco-scheme pe teren arabil (PD-04, PD-05) cu alocări substanțiale.",
    ],
    ancpiMonthlyAvg: "1.290 tranzacții",
    localFaqs: [
      { question: "Unde sunt centrele locale APIA în Călărași?", answer: "La Călărași, Oltenița, Lehliu-Gară și Budești." },
    ],
  },
  "caras-severin": {
    code: "CS",
    name: "Caraș-Severin",
    region: "Vest",
    capital: "Reșița",
    population: "250.000",
    activeImmCount: "8.900",
    adrName: "ADR Vest",
    apiaCenter: "Centrul Județean APIA Caraș-Severin — Str. Republicii nr. 69, Reșița",
    ojfirCenter: "OJFIR Caraș-Severin — Str. Făgărașului nr. 10, Reșița",
    agriculturalSurfaceHa: "400.000 ha (260.000 ha pajiști și fânețe alpine, 130.000 ha arabil)",
    topCrops: ["Pomi fructiferi (Valea Almăjului)", "Porumb", "Grâu", "Plante furajere"],
    topLivestock: ["Ovine Țurcană", "Bovine de carne (Angus, Charolaise)", "Porcine din rasa Mangalița"],
    topIndustries: ["Metalurgie & Construcții Mașini", "Turism Balnear & Montan (Băile Herculane)", "Prelucrare Lemn", "Agroturism"],
    keyIncentives: [
      "Plăți compensatorii masive pentru zone montane ANC ZM.",
      "Sprijin pentru creșterea extensivă a animalelor pe pajiști (PD-07).",
      "Fonduri de Tranziție Justă și dezvoltare rurală ADR Vest.",
    ],
    ancpiMonthlyAvg: "840 tranzacții",
    localFaqs: [
      { question: "Ce sprijin primesc crescătorii de animale pe pajiștile montane din Caraș-Severin?", answer: "Primesc BISS + Eco-schema PD-07 + Sprijinul ANC ZM pentru zone cu constrângeri naturale." },
    ],
  },
  cluj: {
    code: "CJ",
    name: "Cluj",
    region: "Nord-Vest",
    capital: "Cluj-Napoca",
    population: "700.000",
    activeImmCount: "48.500",
    adrName: "ADR Nord-Vest",
    apiaCenter: "Centrul Județean APIA Cluj — Str. Fagului nr. 7, Cluj-Napoca",
    ojfirCenter: "CRFIR 6 Nord-Vest & OJFIR Cluj — Str. Moților nr. 84, Cluj-Napoca",
    agriculturalSurfaceHa: "420.000 ha (175.000 ha arabil, 235.000 ha pășuni și fânețe)",
    topCrops: ["Grâu", "Porumb", "Sfeclă de zahăr", "Cartof", "Leguminoase furajere"],
    topLivestock: ["Bovine lapte (Bălțată Românească)", "Ovine Țurcană", "Avicultură", "Apicultură"],
    topIndustries: ["IT & Software", "Cercetare Agronomică & Biotehnologii (USAMV Cluj)", "Industrie Farmaceutică & Lactate", "Piese Auto"],
    keyIncentives: [
      "Granturi ADR Nord-Vest de până la 200.000 EUR pentru inovare și digitalizare.",
      "Sediu regional CRFIR 6 Nord-Vest pentru depunerea proiectelor mari AFIR.",
      "Sprijin municipal Cluj-Napoca și CJ Cluj pentru start-up-uri agrotech.",
    ],
    ancpiMonthlyAvg: "2.610 tranzacții",
    localFaqs: [
      { question: "Unde se depun proiectele AFIR în regiunea Nord-Vest?", answer: "Depunerea este 100% online pe www.afir.ro, cu sediul regional CRFIR situat în Cluj-Napoca pe Str. Moților." },
    ],
  },
  constanta: {
    code: "CT",
    name: "Constanța",
    region: "Sud-Est",
    capital: "Constanța",
    population: "680.000",
    activeImmCount: "36.000",
    adrName: "ADR Sud-Est",
    apiaCenter: "Centrul Județean APIA Constanța — Str. Mircea cel Bătrân nr. 106, Constanța",
    ojfirCenter: "CRFIR 2 Sud-Est & OJFIR Constanța — Str. Revoluției nr. 19, Constanța",
    agriculturalSurfaceHa: "560.000 ha (480.000 ha teren arabil, Podișul Dobrogei)",
    topCrops: ["Grâu de panificație", "Orz/Orzoaică de bere", "Floarea-soarelui", "Rapiță", "Viță-de-vie (Murfatlar)", "Fructe (Cernavodă)"],
    topLivestock: ["Ovine de lapte și carne (Merinos de Palas)", "Porcine", "Avicultură"],
    topIndustries: ["Transport Maritim & Portuar (Portul Constanța)", "Turism Litoral", "Energie Eoliană & Nucleară", "Agro-logistică Cerealieră"],
    keyIncentives: [
      "Finanțare prioritară pentru reabilitarea sistemelor de irigații din Dobrogea prin Canalul Dunăre-Marea Neagră.",
      "Granturi pentru crame și reconversie viticolă DOC Murfatlar.",
      "Sprijin cuplat pentru oile Merinos de Palas create la Institutul ICDCOC Palas.",
    ],
    ancpiMonthlyAvg: "2.190 tranzacții",
    localFaqs: [
      { question: "Ce măsuri de irigații sunt deschise în județul Constanța?", answer: "Măsura DR-25 pentru organizațiile de udători (OUAI) și proiectele de reabilitare a stațiilor de pompare ANIF." },
    ],
  },
  covasna: {
    code: "CV",
    name: "Covasna",
    region: "Centru",
    capital: "Sfântu Gheorghe",
    population: "205.000",
    activeImmCount: "7.800",
    adrName: "ADR Centru",
    apiaCenter: "Centrul Județean APIA Covasna — Str. Constructorilor nr. 4, Sfântu Gheorghe",
    ojfirCenter: "OJFIR Covasna — Str. 1 Decembrie 1918 nr. 12, Sfântu Gheorghe",
    agriculturalSurfaceHa: "185.000 ha (75.000 ha arabil, 105.000 ha pășuni montane)",
    topCrops: ["Cartof (Bazinul Târgu Secuiesc)", "Sfeclă de zahăr", "Cereale de primăvară", "In și cânepă"],
    topLivestock: ["Bovine lapte", "Ovine de munte", "Creșterea cailor de rasă"],
    topIndustries: ["Procesare Lactate & Brânzeturi", "Confectii", "Procesare Lemn", "Turism Balneoclimateric"],
    keyIncentives: [
      "Subvenții majorate pentru cartoful de sămânță și industrializare.",
      "Plăți compensatorii pentru pajiști cu valoare naturală ridicată (HNV).",
      "Sprijin ADR Centru pentru cooperativele agricole de procesare a laptelui.",
    ],
    ancpiMonthlyAvg: "720 tranzacții",
    localFaqs: [
      { question: "Unde sunt centrele locale APIA în Covasna?", answer: "Sfântu Gheorghe, Târgu Secuiesc, Baraolt, Covasna și Întorsura Buzăului." },
    ],
  },
  dambovita: {
    code: "DB",
    name: "Dâmbovița",
    region: "Sud-Muntenia",
    capital: "Târgoviște",
    population: "485.000",
    activeImmCount: "18.200",
    adrName: "ADR Sud-Muntenia",
    apiaCenter: "Centrul Județean APIA Dâmbovița — Str. I.C. Vissarion nr. 4, Târgoviște",
    ojfirCenter: "CRFIR 3 Sud-Muntenia & OJFIR Dâmbovița — Str. Calea Domnească nr. 216, Târgoviște",
    agriculturalSurfaceHa: "245.000 ha (155.000 ha arabil, 45.000 ha livezi de meri Voinești, 45.000 ha pășuni)",
    topCrops: ["Meri și pruni (Faimosul Bazin Pomicol Voinești)", "Porumb", "Grâu", "Legumicultură (Băleni Dâmbovița)"],
    topLivestock: ["Avicultură", "Bovine lapte", "Ovine"],
    topIndustries: ["Electrocasnice (Arctic Găești)", "Metalurgie", "Pomicultură & Sucuri", "Legumicultură Intensivă"],
    keyIncentives: [
      "Sediul Agenției Regionale CRFIR 3 Sud-Muntenia la Târgoviște.",
      "Granturi pentru livezi de meri și depozite cu atmosferă controlată (DR-16).",
      "Ajutoare de stat pentru legumicultorii din marile bazine legumicole (Băleni/Găești).",
    ],
    ancpiMonthlyAvg: "1.410 tranzacții",
    localFaqs: [
      { question: "Ce sprijin primesc pomicultorii din Bazinul Voinești?", answer: "Sprijinul cuplat PD-15 pentru mere (circa 350-400 EUR/ha) plus granturi AFIR DR-16 pentru reîntinerirea livezilor." },
    ],
  },
  dolj: {
    code: "DJ",
    name: "Dolj",
    region: "Sud-Vest Oltenia",
    capital: "Craiova",
    population: "630.000",
    activeImmCount: "27.000",
    adrName: "ADR Sud-Vest Oltenia",
    apiaCenter: "Centrul Județean APIA Dolj — Str. Severinului nr. 36, Craiova",
    ojfirCenter: "CRFIR 4 Sud-Vest Oltenia & OJFIR Dolj — Str. Libertății nr. 19, Craiova",
    agriculturalSurfaceHa: "585.000 ha (490.000 ha teren arabil extrem de fertil, Câmpia Olteniei)",
    topCrops: ["Grâu", "Porumb", "Floarea-soarelui", "Rapiță", "Pepeni verzi și galbeni (Dăbuleni)", "Legume în solarii (Calafat)"],
    topLivestock: ["Ovine", "Bovine de carne", "Porcine", "Apicultură"],
    topIndustries: ["Automotive (Ford Otosan Craiova)", "Industrie Aeronautică", "Agro-logistică Cerealieră", "Silozuri & Morărit"],
    keyIncentives: [
      "Sediul Regional CRFIR 4 Sud-Vest Oltenia situat în Craiova.",
      "Fondul de Tranziție Justă pentru crearea de noi locuri de muncă durabile.",
      "Reabilitarea amenajărilor hidroameliorative împotriva deșertificării în sudul județului (Sahara Olteniei / Dăbuleni).",
      "Sprijin cuplat pentru pepeni și legume în solarii.",
    ],
    ancpiMonthlyAvg: "1.760 tranzacții",
    localFaqs: [
      { question: "Există fonduri speciale pentru combaterea secetei în sudul Doljului?", answer: "Da, prin programele de împădurire a terenurilor degradate (PNRR) și granturile de irigații DR-25/DR-26." },
    ],
  },
  galati: {
    code: "GL",
    name: "Galați",
    region: "Sud-Est",
    capital: "Galați",
    population: "500.000",
    activeImmCount: "19.500",
    adrName: "ADR Sud-Est",
    apiaCenter: "Centrul Județean APIA Galați — Str. Domnească nr. 120, Galați",
    ojfirCenter: "OJFIR Galați — Str. Brăilei nr. 159, Galați",
    agriculturalSurfaceHa: "355.000 ha (280.000 ha arabil, Podișul Covurlui / Câmpia Tecuciului)",
    topCrops: ["Legumicultură în spații protejate (Bazinul Matca - cel mai mare din țară)", "Grâu", "Floarea-soarelui", "Porumb", "Viță-de-vie (Ivești, Nicorești)"],
    topLivestock: ["Ovine", "Bovine", "Avicultură"],
    topIndustries: ["Siderurgie (Liberty Galați)", "Șantier Naval", "Legumicultură & Solarii", "Vinificație"],
    keyIncentives: [
      "Concentrare masivă de fonduri pentru legumicultură în Bazinul Matca (Programul Tomata, PD-13).",
      "Granturi pentru depozite frigorifice și centre de sortare legume.",
      "Sprijin pentru cramele de tradiție din arealele Nicorești și Ivești.",
    ],
    ancpiMonthlyAvg: "1.320 tranzacții",
    localFaqs: [
      { question: "Câte solarii sunt finanțate în bazinul Matca?", answer: "Matca găzduiește peste 1.000 de hectare de solarii, fiind principalul beneficiar național al ajutoarelor de minimis pentru tomate și legume protejate." },
    ],
  },
  giurgiu: {
    code: "GR",
    name: "Giurgiu",
    region: "Sud-Muntenia",
    capital: "Giurgiu",
    population: "260.000",
    activeImmCount: "9.600",
    adrName: "ADR Sud-Muntenia",
    apiaCenter: "Centrul Județean APIA Giurgiu — Str. Mihai Viteazul nr. 14, Giurgiu",
    ojfirCenter: "OJFIR Giurgiu — Str. Vlad Țepeș nr. 8, Giurgiu",
    agriculturalSurfaceHa: "275.000 ha (peste 245.000 ha arabil Clasa I, Câmpia Burnazului)",
    topCrops: ["Grâu", "Porumb", "Floarea-soarelui", "Rapiță", "Soia", "Lucernă"],
    topLivestock: ["Porcine în ferme intensive", "Avicultură", "Bovine carne"],
    topIndustries: ["Port Fluvial Giurgiu & Terminale Cerealiere", "Industrie Alimentară", "Producție Materiale Construcții"],
    keyIncentives: [
      "Incentive pentru silozuri și transfer fluvial de cereale către Portul Constanța.",
      "Granturi pentru sisteme de irigații alimentate direct din fluviul Dunărea.",
      "Sprijin redistributiv CRISS și eco-scheme pe teren arabil.",
    ],
    ancpiMonthlyAvg: "1.150 tranzacții",
    localFaqs: [
      { question: "Unde sunt centrele locale APIA în Giurgiu?", answer: "Giurgiu, Bolintin-Vale, Ghimpați și Mihăilești." },
    ],
  },
  gorj: {
    code: "GJ",
    name: "Gorj",
    region: "Sud-Vest Oltenia",
    capital: "Târgu Jiu",
    population: "315.000",
    activeImmCount: "11.200",
    adrName: "ADR Sud-Vest Oltenia",
    apiaCenter: "Centrul Județean APIA Gorj — Str. Victoriei nr. 132, Târgu Jiu",
    ojfirCenter: "OJFIR Gorj — Str. Tudor Vladimirescu nr. 28, Târgu Jiu",
    agriculturalSurfaceHa: "240.000 ha (140.000 ha pășuni montane, 90.000 ha arabil)",
    topCrops: ["Pomi fructiferi", "Porumb", "Cereale furajere", "Plantații de nuci"],
    topLivestock: ["Ovine de munte (Transalpina)", "Bovine lapte/carne", "Apicultură"],
    topIndustries: ["Energie (Complexul Energetic Oltenia)", "Turism Montan & Cultural (Brâncuși)", "Fondul de Tranziție Justă", "Textile"],
    keyIncentives: [
      "Finanțare majoră prin Fondul pentru o Tranziție Justă (FTJ) pentru diversificarea economiei locale.",
      "Plăți pentru agricultură ecologică și pășunat extensiv în zona subcarpatică.",
      "Sprijin pentru tinerii fermieri din comunitățile miniere reconvertite.",
    ],
    ancpiMonthlyAvg: "960 tranzacții",
    localFaqs: [
      { question: "Pot accesa fermierii din Gorj Fondul de Tranziție Justă?", answer: "Da, microîntreprinderile și IMM-urile din Gorj au alocate granturi nerambursabile speciale pentru activități economice noi și agroturism." },
    ],
  },
  harghita: {
    code: "HR",
    name: "Harghita",
    region: "Centru",
    capital: "Miercurea Ciuc",
    population: "300.000",
    activeImmCount: "10.500",
    adrName: "ADR Centru",
    apiaCenter: "Centrul Județean APIA Harghita — Str. Progresului nr. 18, Miercurea Ciuc",
    ojfirCenter: "OJFIR Harghita — Str. Petőfi Sándor nr. 34, Miercurea Ciuc",
    agriculturalSurfaceHa: "340.000 ha (250.000 ha pajiști alpine/fânețe montane, 80.000 ha arabil)",
    topCrops: ["Cartof de consum și sămânță (Depresiunea Ciucului)", "Secară", "Trifoi și lucernă montană", "Plante medicinale"],
    topLivestock: ["Bovine de lapte (Bălțată Românească, Pinzgau)", "Ovine Țurcană", "Cai de rasă"],
    topIndustries: ["Prelucrare Lemn", "Industrie Alimentară & Lactate (Gordon, Harghita)", "Ape Minerale (Borsec, Tușnad)", "Turism Balnear"],
    keyIncentives: [
      "Subvenții compensatorii substanțiale pentru zone cu constrângeri naturale extreme (ANC ZM).",
      "Pachete de agro-mediu pentru cosit tradițional manual pe pajiști de mare valoare ecologică.",
      "Sprijin cuplat pentru cartof și lapte de vacă.",
    ],
    ancpiMonthlyAvg: "780 tranzacții",
    localFaqs: [
      { question: "Ce măsuri de cosit tradițional sunt plătite în Harghita?", answer: "Pachetele Măsurii 10 / DR-01 pentru cositul manual pe parcele montane cu un cuantum de până la 180-250 EUR/ha." },
    ],
  },
  hunedoara: {
    code: "HD",
    name: "Hunedoara",
    region: "Vest",
    capital: "Deva",
    population: "360.000",
    activeImmCount: "13.600",
    adrName: "ADR Vest",
    apiaCenter: "Centrul Județean APIA Hunedoara — Str. 22 Decembrie nr. 222, Deva",
    ojfirCenter: "OJFIR Hunedoara — Bulevardul 1 Decembrie 1918 nr. 30, Deva",
    agriculturalSurfaceHa: "310.000 ha (210.000 ha pășuni montane / Țara Hațegului / Țara Zarandului, 90.000 ha arabil)",
    topCrops: ["Pomi fructiferi", "Cereale furajere", "Porumb", "Plante de nutreț"],
    topLivestock: ["Ovine de munte (Țurcană Brează de Hațeg)", "Bovine de carne", "Piscicultură montană"],
    topIndustries: ["Fondul de Tranziție Justă (Valea Jiului)", "Turism Cultural & Montan (Castelul Corvinilor, Retezat)", "Componente Auto"],
    keyIncentives: [
      "Granturi speciale FTJ pentru antreprenoriat și agroturism în Valea Jiului și Hunedoara.",
      "Sprijin cuplat pentru oile Breaza de Hațeg (ecotip de elită).",
      "Plăți pentru menținerea pajiștilor din Parcul Național Retezat.",
    ],
    ancpiMonthlyAvg: "1.140 tranzacții",
    localFaqs: [
      { question: "Unde sunt centrele locale APIA în Hunedoara?", answer: "Deva, Hunedoara, Hațeg, Brad, Petroșani, Orăștie și Ilia." },
    ],
  },
  ialomita: {
    code: "IL",
    name: "Ialomița",
    region: "Sud-Muntenia",
    capital: "Slobozia",
    population: "250.000",
    activeImmCount: "10.200",
    adrName: "ADR Sud-Muntenia",
    apiaCenter: "Centrul Județean APIA Ialomița — Str. Lacului nr. 2, Slobozia",
    ojfirCenter: "OJFIR Ialomița — Bulevardul Matei Basarab nr. 27, Slobozia",
    agriculturalSurfaceHa: "375.000 ha (340.000 ha arabil de înaltă fertilitate, Bărăgan)",
    topCrops: ["Grâu", "Porumb", "Floarea-soarelui", "Rapiță", "Orz", "Soia", "Lucernă"],
    topLivestock: ["Porcine în complexe mari", "Avicultură", "Ovine"],
    topIndustries: ["Agro-business & Silozuri (Bărăgan)", "Industrie Alimentară & Ulei Vegetal (Expur)", "Procesare Carne"],
    keyIncentives: [
      "Granturi pentru modernizarea marilor ferme cerealiere prin DR-15.",
      "Modernizarea rețelelor de irigații pe râul Ialomița și Dunăre (DR-25).",
      "Ajutoare de stat pentru motorină și despăgubiri de secetă.",
    ],
    ancpiMonthlyAvg: "1.190 tranzacții",
    localFaqs: [
      { question: "Ce suprafață agricolă este irigată în Ialomița?", answer: "Județul Ialomița deține unele dintre cele mai mari suprafețe amenajate pentru irigații din Bărăgan, extinse prin măsura DR-25." },
    ],
  },
  iasi: {
    code: "IS",
    name: "Iași",
    region: "Nord-Est",
    capital: "Iași",
    population: "790.000",
    activeImmCount: "34.500",
    adrName: "ADR Nord-Est",
    apiaCenter: "Centrul Județean APIA Iași — Str. Dumbrava Roșie nr. 3, Iași",
    ojfirCenter: "CRFIR 1 Nord-Est & OJFIR Iași — Str. Moara de Foc nr. 35, Iași",
    agriculturalSurfaceHa: "380.000 ha (255.000 ha arabil, 90.000 ha pășuni, 30.000 ha vii/livezi)",
    topCrops: ["Grâu", "Porumb", "Floarea-soarelui", "Soia", "Viță-de-vie (Cotnari, Bucium)", "Livezi de cireși și meri (Sârca)"],
    topLivestock: ["Bovine lapte", "Ovine (Carabașă și Țurcană)", "Avicultură", "Apicultură"],
    topIndustries: ["IT & Software", "Sediul Regional CRFIR 1 Nord-Est", "Industrie Farmaceutică (Antibiotice)", "Vinificație de Top (Cotnari)"],
    keyIncentives: [
      "Sediul Agenției Regionale CRFIR 1 Nord-Est gestionând fondurile FEADR pentru 6 județe.",
      "Sprijin de reconversie viticolă în arealele celebre Cotnari și Dealurile Moldovei.",
      "Granturi ADR Nord-Est pentru digitalizare și agro-tehnologii.",
    ],
    ancpiMonthlyAvg: "1.980 tranzacții",
    localFaqs: [
      { question: "Unde se depun proiectele AFIR pentru regiunea Nord-Est?", answer: "Online pe www.afir.ro, cu structura regională CRFIR 1 situată în municipiul Iași." },
    ],
  },
  ilfov: {
    code: "IF",
    name: "Ilfov",
    region: "București-Ilfov",
    capital: "Buftea",
    population: "540.000",
    activeImmCount: "39.000",
    adrName: "ADR București-Ilfov",
    apiaCenter: "Centrul APIA Ilfov — Bulevardul Carol I nr. 12, București",
    ojfirCenter: "OJFIR Ilfov — Str. Știrbei Vodă nr. 43, București",
    agriculturalSurfaceHa: "95.000 ha (80.000 ha arabil periurban, sere de legume)",
    topCrops: ["Legume în spații protejate (Vidra, Copăceni, Jilava)", "Grâu", "Rapiță", "Plante ornamentale"],
    topLivestock: ["Avicultură", "Echitatie & herghelii", "Bovine carne"],
    topIndustries: ["Logistică & Huburi de Depozitare", "Comerț & Distribuție", "Industrie Alimentară Periurbană", "Construcții"],
    keyIncentives: [
      "Finanțare pentru sere hidroponice moderne cu desfacere directă pe piața Capitalei.",
      "Huburi logistice și depozite frigorifice alimentare.",
      "Sprijin ADR București-Ilfov pentru microîntreprinderi periurbane.",
    ],
    ancpiMonthlyAvg: "3.745 tranzacții",
    localFaqs: [
      { question: "Ce oportunități au fermele legumicole din Ilfov?", answer: "Acces direct la rețelele de supermarketuri din București, sprijinul cuplat PD-13 pentru sere și granturile de modernizare." },
    ],
  },
  maramures: {
    code: "MM",
    name: "Maramureș",
    region: "Nord-Vest",
    capital: "Baia Mare",
    population: "460.000",
    activeImmCount: "18.500",
    adrName: "ADR Nord-Vest",
    apiaCenter: "Centrul Județean APIA Maramureș — Str. Victoriei nr. 143, Baia Mare",
    ojfirCenter: "OJFIR Maramureș — Str. Gheorghe Șincai nr. 46, Baia Mare",
    agriculturalSurfaceHa: "310.000 ha (220.000 ha fânețe și pășuni montane tradiționale, 80.000 ha arabil)",
    topCrops: ["Pomi fructiferi (Prunul de Maramureș - Bazinul Seini/Baia Mare)", "Cartof", "Cereale furajere", "Fructe de pădure"],
    topLivestock: ["Bovine lapte (rase de munte)", "Ovine Țurcană", "Apicultură montană"],
    topIndustries: ["Prelucrare Lemn & Mobilă", "Turism Tradițional & Agroturism", "Lactate Tradiționale", "Electrotehnică"],
    keyIncentives: [
      "Pachete substanțiale de agro-mediu pentru cositul tradițional manual și menținerea peisajului cultural.",
      "Plăți pentru agricultura ecologică certificată.",
      "Granturi pentru distilerii artizanale și procesare tradițională a fructelor.",
    ],
    ancpiMonthlyAvg: "1.250 tranzacții",
    localFaqs: [
      { question: "Unde sunt centrele locale APIA în Maramureș?", answer: "Baia Mare, Sighetu Marmației, Vișeu de Sus, Târgu Lăpuș, Șomcuta Mare și Seini." },
    ],
  },
  mehedinti: {
    code: "MH",
    name: "Mehedinți",
    region: "Sud-Vest Oltenia",
    capital: "Drobeta-Turnu Severin",
    population: "235.000",
    activeImmCount: "8.500",
    adrName: "ADR Sud-Vest Oltenia",
    apiaCenter: "Centrul Județean APIA Mehedinți — Str. Traian nr. 87, Drobeta-Turnu Severin",
    ojfirCenter: "OJFIR Mehedinți — Bulevardul Carol I nr. 75, Drobeta-Turnu Severin",
    agriculturalSurfaceHa: "295.000 ha (180.000 ha arabil, 90.000 ha pășuni, 20.000 ha vii/livezi)",
    topCrops: ["Viță-de-vie (Arealul Corcova, Orevița)", "Grâu", "Porumb", "Floarea-soarelui", "Smochine și migdale (climat submediteranean Svinița)"],
    topLivestock: ["Ovine", "Caprine", "Bovine carne", "Apicultură"],
    topIndustries: ["Energie Hidroelectrică (Porțile de Fier)", "Construcții Navale", "Vinificație DOC Corcova", "Turism Clisura Dunării"],
    keyIncentives: [
      "Granturi AFIR pentru crame și turism oenologic în podgoriile mehedințene.",
      "Sprijin pentru caprine și ovine în zona de deal și Clisura Dunării.",
      "Plăți directe BISS și ajutoare de stat pentru culturi de câmp.",
    ],
    ancpiMonthlyAvg: "780 tranzacții",
    localFaqs: [
      { question: "Există culturi speciale finanțate în Mehedinți?", answer: "Datorită microclimatului submediteranean, livezile de smochini (Svinița) și podgoriile (Corcova) beneficiază de măsuri specifice." },
    ],
  },
  mures: {
    code: "MS",
    name: "Mureș",
    region: "Centru",
    capital: "Târgu Mureș",
    population: "520.000",
    activeImmCount: "23.400",
    adrName: "ADR Centru",
    apiaCenter: "Centrul Județean APIA Mureș — Str. Insulei nr. 2, Târgu Mureș",
    ojfirCenter: "OJFIR Mureș — Str. Călărașilor nr. 31, Târgu Mureș",
    agriculturalSurfaceHa: "410.000 ha (220.000 ha arabil, 175.000 ha pășuni/fânețe)",
    topCrops: ["Sfeclă de zahăr (Fabrica de Zahăr Luduș)", "Porumb", "Soia", "Grâu", "Livezi de meri (Bazinul Reghin)", "Hamei (Sighișoara)"],
    topLivestock: ["Bovine lapte (nucleu genetic Bălțată)", "Avicultură", "Ovine", "Porcine"],
    topIndustries: ["Industrie Farmaceutică", "Procesare Zahăr & Lactate", "Mobilă & Lemn (Reghin)", "Gaz Metan & Chimie"],
    keyIncentives: [
      "Sprijin cuplat vegetal pentru sfecla de zahăr legată de funcționarea Fabricii Luduș.",
      "Sprijin pentru cultura hameiului (PD-19).",
      "Granturi pentru livezi și depozite pomicole pe Valea Gurghiului.",
    ],
    ancpiMonthlyAvg: "1.650 tranzacții",
    localFaqs: [
      { question: "Cât este sprijinul cuplat pentru sfecla de zahăr în Mureș?", answer: "Cuantumul depășește adesea 800–1.000 EUR/hectar pentru fermierii care dețin contract de livrare cu fabrica de zahăr." },
    ],
  },
  neamt: {
    code: "NT",
    name: "Neamț",
    region: "Nord-Est",
    capital: "Piatra Neamț",
    population: "450.000",
    activeImmCount: "15.800",
    adrName: "ADR Nord-Est",
    apiaCenter: "Centrul Județean APIA Neamț — Str. Alexandru cel Bun nr. 19, Piatra Neamț",
    ojfirCenter: "OJFIR Neamț — Bulevardul Decebal nr. 35, Piatra Neamț",
    agriculturalSurfaceHa: "285.000 ha (160.000 ha arabil fertil pe Valea Siretului/Moldovei, 115.000 ha pășuni montane)",
    topCrops: ["Porumb", "Grâu", "Sfeclă de zahăr (Roman)", "Floarea-soarelui", "Cartof"],
    topLivestock: ["Bovine lapte", "Ovine Țurcană", "Piscicultură (păstrăvării montane)"],
    topIndustries: ["Procesare Zahăr (Tereos Roman)", "Țevi Sudate (ArcelorMittal Roman)", "Industrie Alimentară & Lactate", "Turism Ecumenic"],
    keyIncentives: [
      "Sprijin cuplat pentru sfecla de zahăr și culturile de câmp din Câmpia Romanului.",
      "Plăți pentru agroturism și pensiuni în zona Ceahlău / Vânători-Neamț.",
      "Plăți compensatorii pentru zone montane defavorizate.",
    ],
    ancpiMonthlyAvg: "1.280 tranzacții",
    localFaqs: [
      { question: "Unde sunt centrele locale APIA în Neamț?", answer: "Piatra Neamț, Roman, Târgu Neamț, Roznov și Bicaz." },
    ],
  },
  olt: {
    code: "OT",
    name: "Olt",
    region: "Sud-Vest Oltenia",
    capital: "Slatina",
    population: "385.000",
    activeImmCount: "14.500",
    adrName: "ADR Sud-Vest Oltenia",
    apiaCenter: "Centrul Județean APIA Olt — Str. Arcului nr. 1, Slatina",
    ojfirCenter: "OJFIR Olt — Str. Lipscani nr. 42, Slatina",
    agriculturalSurfaceHa: "440.000 ha (370.000 ha arabil fertil, Câmpia Boianului / Valea Oltului)",
    topCrops: ["Legumicultură în solarii (Bazinele celebre Izbiceni, Tia Mare, Cilieni, Pleșoiu)", "Grâu", "Porumb", "Floarea-soarelui", "Rapiță"],
    topLivestock: ["Porcine", "Ovine", "Bovine carne", "Avicultură"],
    topIndustries: ["Aluminiu (Alro Slatina)", "Producție Cablaje & Anvelope (Pirelli)", "Legumicultură Intensivă", "Silozuri Cerealier"],
    keyIncentives: [
      "Concentrare majoră de fonduri pentru legumicultură protejată (Programul Tomata, Usturoiul Românesc, PD-13).",
      "Granturi pentru cooperative legumicole și depozite climatizate în bazinul Izbiceni.",
      "Investiții în irigații la nivel de fermă prin DR-26.",
    ],
    ancpiMonthlyAvg: "1.380 tranzacții",
    localFaqs: [
      { question: "De ce este Izbiceni un pol legumicol național?", answer: "Comuna Izbiceni și localitățile vecine dețin mii de hectare de solarii încălzite, livrând legume proaspete tot timpul anului." },
    ],
  },
  prahova: {
    code: "PH",
    name: "Prahova",
    region: "Sud-Muntenia",
    capital: "Ploiești",
    population: "720.000",
    activeImmCount: "35.000",
    adrName: "ADR Sud-Muntenia",
    apiaCenter: "Centrul Județean APIA Prahova — Str. Anton Pann nr. 7, Ploiești",
    ojfirCenter: "OJFIR Prahova — Str. Gheorghe Grigore Cantacuzino nr. 42, Ploiești",
    agriculturalSurfaceHa: "275.000 ha (145.000 ha arabil, 85.000 ha pășuni montane, 45.000 ha vii și livezi)",
    topCrops: ["Viță-de-vie (Inima Podgoriei Dealu Mare: Valea Călugărească, Tohani, Ceptura)", "Pomi fructiferi (Prahova de Mijloc)", "Porumb", "Grâu"],
    topLivestock: ["Avicultură", "Bovine lapte", "Ovine", "Apicultură"],
    topIndustries: ["Rafinare & Petrochimie", "Vinificație de Elită (Dealu Mare)", "Turism Valea Prahovei", "Logistică & Parcuri Industriale"],
    keyIncentives: [
      "Granturi AFIR pentru crame moderne, oenoturism și vinuri cu Denumire de Origine Controlată (DOC).",
      "Reconversie viticolă plătită prin APIA.",
      "Finanțări ADR Sud-Muntenia pentru procesare agroalimentară și tranziție verde.",
    ],
    ancpiMonthlyAvg: "2.150 tranzacții",
    localFaqs: [
      { question: "Ce oportunități de reconversie viticolă sunt în Podgoria Dealu Mare?", answer: "Fermierii pot primi până la 12.000 EUR/ha pentru defrișarea viilor vechi și plantarea de soiuri nobile certificate." },
    ],
  },
  "satu-mare": {
    code: "SM",
    name: "Satu Mare",
    region: "Nord-Vest",
    capital: "Satu Mare",
    population: "330.000",
    activeImmCount: "13.900",
    adrName: "ADR Nord-Vest",
    apiaCenter: "Centrul Județean APIA Satu Mare — Str. 1 Decembrie 1918 nr. 15, Satu Mare",
    ojfirCenter: "OJFIR Satu Mare — Str. Mihai Viteazul nr. 10, Satu Mare",
    agriculturalSurfaceHa: "320.000 ha (225.000 ha arabil fertil, Câmpia Someșului, 35.000 ha vii/livezi Țara Oașului)",
    topCrops: ["Porumb", "Grâu", "Floarea-soarelui", "Căpșuni (Bazinul Halmeu - cel mai mare din țară)", "Pomi fructiferi", "Viță-de-vie (Beltiug)"],
    topLivestock: ["Porcine", "Bovine lapte", "Avicultură", "Apicultură"],
    topIndustries: ["Componente Auto", "Industrie Alimentară & Sucuri", "Cultura Căpșunului", "Distilate Tradiționale (Pălincă de Oaș)"],
    keyIncentives: [
      "Subvenții specifice pentru culturile de căpșuni din bazinul Halmeu.",
      "Granturi pentru distilerii și certificare produse tradiționale protejate (IGP/DOC Pălincă).",
      "Fonduri de irigații și drenaj în Câmpia Someșului.",
    ],
    ancpiMonthlyAvg: "1.120 tranzacții",
    localFaqs: [
      { question: "Ce sprijin primesc cultivatorii de căpșuni din Halmeu?", answer: "Sprijinul cuplat pentru fructe, ajutoare de minimis și granturi AFIR pentru solarii și depozite frigorifice." },
    ],
  },
  salaj: {
    code: "SJ",
    name: "Sălaj",
    region: "Nord-Vest",
    capital: "Zalău",
    population: "215.000",
    activeImmCount: "8.900",
    adrName: "ADR Nord-Vest",
    apiaCenter: "Centrul Județean APIA Sălaj — Str. Gheorghe Doja nr. 17, Zalău",
    ojfirCenter: "OJFIR Sălaj — Str. Unirii nr. 19, Zalău",
    agriculturalSurfaceHa: "240.000 ha (120.000 ha arabil, 95.000 ha fânețe/pășuni, 25.000 ha livezi de pruni)",
    topCrops: ["Livezi de prun și măr", "Porumb", "Grâu", "Viță-de-vie (Șimleu Silvaniei - spumante)"],
    topLivestock: ["Bovine lapte/carne", "Ovine", "Porcine (Mangalița și Bazna)"],
    topIndustries: ["Producție Țevi Industriale (TenarisSilcotub)", "Vinuri Spumante", "Distilate Pomicole (Pălincă de Zalău)", "Mobilă"],
    keyIncentives: [
      "Sprijin pentru rase autohtone de porci pe cale de dispariție (Bazna și Mangalița).",
      "Plăți pentru menținerea livezilor tradiționale de pruni.",
      "Granturi ADR Nord-Vest pentru meșteșuguri și microindustrializare rurală.",
    ],
    ancpiMonthlyAvg: "740 tranzacții",
    localFaqs: [
      { question: "Unde sunt centrele locale APIA în Sălaj?", answer: "Zalău, Șimleu Silvaniei, Jibou, Cehu Silvaniei și Crasna." },
    ],
  },
  sibiu: {
    code: "SB",
    name: "Sibiu",
    region: "Centru",
    capital: "Sibiu",
    population: "420.000",
    activeImmCount: "24.000",
    adrName: "ADR Centru",
    apiaCenter: "Centrul Județean APIA Sibiu — Str. Someșului nr. 49, Sibiu",
    ojfirCenter: "OJFIR Sibiu — Str. Hipodromului nr. 2A, Sibiu",
    agriculturalSurfaceHa: "285.000 ha (180.000 ha pășuni montane / Mărginimea Sibiului, 95.000 ha arabil)",
    topCrops: ["Cereale furajere", "Porumb", "Plante medicinale", "Cartof"],
    topLivestock: ["Ovine Țurcană (Mărginimea Sibiului — Telemea de Sibiu IGP)", "Bovine lapte", "Bivolițe"],
    topIndustries: ["Componente Auto", "IT & Inovare", "Turism Cultural & Gastronomic", "Procesare Tradițională Lactate"],
    keyIncentives: [
      "Sprijin pentru produsele cu Indicație Geografică Protejată (Telemeaua de Sibiu IGP).",
      "Plăți de agro-mediu pe pajiștile alpine din Munții Cindrel și Făgăraș.",
      "Linii de finanțare ADR Centru pentru lanțuri scurte de aprovizionare alimentară.",
    ],
    ancpiMonthlyAvg: "1.650 tranzacții",
    localFaqs: [
      { question: "Ce avantaje au producătorii de Telemea de Sibiu IGP?", answer: "Punctaj suplimentar la toate măsurile de investiții AFIR și acces prioritar la schemele de calitate europene." },
    ],
  },
  suceava: {
    code: "SV",
    name: "Suceava",
    region: "Nord-Est",
    capital: "Suceava",
    population: "640.000",
    activeImmCount: "25.000",
    adrName: "ADR Nord-Est",
    apiaCenter: "Centrul Județean APIA Suceava — Str. Vasile Lupu nr. 22, Suceava",
    ojfirCenter: "OJFIR Suceava — Str. Universității nr. 18, Suceava",
    agriculturalSurfaceHa: "350.000 ha (230.000 ha pășuni montane / Bucovina, 110.000 ha arabil)",
    topCrops: ["Cartof (Bazinul Rădăuți)", "Secară și orz", "Cereale furajere", "Fructe de pădure"],
    topLivestock: ["Bovine lapte (Bălțată și Brună de Maramureș)", "Ovine Țurcană", "Păstrăvării montane"],
    topIndustries: ["Prelucrarea Lemnului (Schweighofer, Egger)", "Turism Bucovina & Agroturism", "Industrie Alimentară & Lactate (Dorna, Rarăul)", "Comerț"],
    keyIncentives: [
      "Sprijin financiar pentru pensiuni și agroturism în zona Bucovinei prin DR-28.",
      "Plăți compensatorii ANC ZM pentru fermele de bovine de lapte din zona montană.",
      "Granturi pentru microîntreprinderi de prelucrare a laptelui și ciupercilor/fructelor de pădure.",
    ],
    ancpiMonthlyAvg: "1.850 tranzacții",
    localFaqs: [
      { question: "Unde sunt centrele locale APIA în județul Suceava?", answer: "Suceava, Rădăuți, Fălticeni, Câmpulung Moldovenesc, Vatra Dornei și Gura Humorului." },
    ],
  },
  teleorman: {
    code: "TR",
    name: "Teleorman",
    region: "Sud-Muntenia",
    capital: "Alexandria",
    population: "340.000",
    activeImmCount: "11.000",
    adrName: "ADR Sud-Muntenia",
    apiaCenter: "Centrul Județean APIA Teleorman — Str. Dunării nr. 180, Alexandria",
    ojfirCenter: "OJFIR Teleorman — Str. Libertății nr. 1, Alexandria",
    agriculturalSurfaceHa: "500.000 ha (peste 460.000 ha teren arabil Clasa I, Câmpia Teleormanului)",
    topCrops: ["Grâu", "Porumb", "Floarea-soarelui", "Rapiță", "Orz", "Soia"],
    topLivestock: ["Ovine", "Porcine", "Bovine carne"],
    topIndustries: ["Agro-business & Comerț Cereale", "Industrie Alimentară & Morărit", "Construcții"],
    keyIncentives: [
      "Eco-scheme pe teren arabil (PD-04, PD-05) cu plăți substanțiale pe marile exploatații.",
      "Proiecte de irigații OUAI alimentate din Dunăre și râul Olt.",
      "Ajutoare de stat pentru compensarea pierderilor cauzate de seceta pedologică.",
    ],
    ancpiMonthlyAvg: "1.260 tranzacții",
    localFaqs: [
      { question: "Unde sunt centrele locale APIA în Teleorman?", answer: "Alexandria, Roșiorii de Vede, Turnu Măgurele, Zimnicea și Videle." },
    ],
  },
  timis: {
    code: "TM",
    name: "Timiș",
    region: "Vest",
    capital: "Timișoara",
    population: "650.000",
    activeImmCount: "38.200",
    adrName: "ADR Vest",
    apiaCenter: "Centrul Județean APIA Timiș — Str. Paris nr. 2A, Timișoara",
    ojfirCenter: "CRFIR 5 Vest & OJFIR Timiș — Str. Lorena nr. 35, Timișoara",
    agriculturalSurfaceHa: "695.000 ha (530.000 ha teren arabil de mare productivitate — cel mai mare din țară)",
    topCrops: ["Grâu", "Porumb", "Floarea-soarelui", "Soia", "Rapiță", "Viță-de-vie (Recaș, Silagiu)"],
    topLivestock: ["Porcine (Smithfield/Comtim)", "Bovine de lapte și carne", "Ovine", "Avicultură"],
    topIndustries: ["Automotive & Electronice (Continental)", "Agro-industrial de mare anvergură", "Vinificație de Top (Cramele Recaș)", "IT & Software"],
    keyIncentives: [
      "Sediul Agenției Regionale CRFIR 5 Vest situat în Timișoara.",
      "Granturi pentru mega-ferme și silozuri moderne prin DR-15.",
      "Sprijin majorat pentru culturile proteice (soia PD-09) și reconversie viticolă Recaș.",
    ],
    ancpiMonthlyAvg: "2.340 tranzacții",
    localFaqs: [
      { question: "Care este cel mai mare județ agricol din România?", answer: "Județul Timiș deține cea mai mare suprafață arabilă din țară (peste 530.000 ha) și cele mai mari efective de porcine." },
    ],
  },
  tulcea: {
    code: "TL",
    name: "Tulcea",
    region: "Sud-Est",
    capital: "Tulcea",
    population: "195.000",
    activeImmCount: "8.200",
    adrName: "ADR Sud-Est",
    apiaCenter: "Centrul Județean APIA Tulcea — Str. Babadag nr. 140, Tulcea",
    ojfirCenter: "OJFIR Tulcea — Str. Isaccei nr. 73, Tulcea",
    agriculturalSurfaceHa: "360.000 ha (280.000 ha arabil, Podișul Nord-Dobrogean / Rezervația Biosferei Delta Dunării)",
    topCrops: ["Grâu", "Floarea-soarelui", "Porumb", "Viță-de-vie (Sarica Niculițel, Babadag)", "Agricultură Ecologică"],
    topLivestock: ["Ovine", "Piscicultură & Acvacultură (Delta Dunării)", "Bovine carne"],
    topIndustries: ["Șantier Naval (VARD Tulcea)", "Pescuit & Prelucrare Pește", "Vinificație DOC Sarica Niculițel", "Turism Delta Dunării"],
    keyIncentives: [
      "Alocare Financiară Specială ITI Delta Dunării (Investiții Teritoriale Integrate) cu linii dedicate de grant.",
      "Plăți pentru agricultura ecologică certificată și conservarea biodiversității în RBDD.",
      "Sprijin specific pentru acvacultură și bazine piscicole prin POPAM.",
    ],
    ancpiMonthlyAvg: "790 tranzacții",
    localFaqs: [
      { question: "Ce este mecanismul ITI Delta Dunării?", answer: "Un instrument financiar dedicat care alocă fonduri europene exclusive pentru județul Tulcea și Rezervația Biosferei Delta Dunării." },
    ],
  },
  vaslui: {
    code: "VS",
    name: "Vaslui",
    region: "Nord-Est",
    capital: "Vaslui",
    population: "375.000",
    activeImmCount: "10.800",
    adrName: "ADR Nord-Est",
    apiaCenter: "Centrul Județean APIA Vaslui — Str. Călugăreni nr. 101, Vaslui",
    ojfirCenter: "OJFIR Vaslui — Str. Ștefan cel Mare nr. 64, Vaslui",
    agriculturalSurfaceHa: "400.000 ha (290.000 ha arabil, Podișul Bârladului, 20.000 ha vii)",
    topCrops: ["Grâu", "Porumb", "Floarea-soarelui", "Viță-de-vie (Huși - Podgoria Fetească Regală)", "Plante furajere"],
    topLivestock: ["Ovine", "Bovine carne", "Avicultură", "Apicultură"],
    topIndustries: ["Industrie Alimentară & Vinuri (Huși)", "Rulmenți (Bârlad)", "Confecții", "Abatoare Pasăre (Safir)"],
    keyIncentives: [
      "Granturi AFIR pentru tineri fermieri DR-30 și consolidarea fermelor de familie.",
      "Sprijin de reconversie viticolă în faimoasa Podgorie a Hușilor.",
      "Ajutoare de stat pentru amenajări antierozionale pe terenurile în pantă din Podișul Bârladului.",
    ],
    ancpiMonthlyAvg: "990 tranzacții",
    localFaqs: [
      { question: "Unde sunt centrele locale APIA în Vaslui?", answer: "Vaslui, Bârlad, Huși, Negrești și Murgeni." },
    ],
  },
  valcea: {
    code: "VL",
    name: "Vâlcea",
    region: "Sud-Vest Oltenia",
    capital: "Râmnicu Vâlcea",
    population: "350.000",
    activeImmCount: "13.800",
    adrName: "ADR Sud-Vest Oltenia",
    apiaCenter: "Centrul Județean APIA Vâlcea — Str. Gib Mihăescu nr. 41, Râmnicu Vâlcea",
    ojfirCenter: "OJFIR Vâlcea — Str. Calea lui Traian nr. 135, Râmnicu Vâlcea",
    agriculturalSurfaceHa: "240.000 ha (140.000 ha pășuni montane / Depresiunea Horezu, 70.000 ha arabil, 30.000 ha livezi/vii)",
    topCrops: ["Pomi fructiferi (Bazinul Drăgășani / Horezu)", "Viță-de-vie (Podgoria Drăgășani - Crâmpoșie Selecționată)", "Cereale"],
    topLivestock: ["Ovine de munte (Valea Lotrului)", "Bovine lapte", "Apicultură"],
    topIndustries: ["Chimie (Oltchim/Chimcomplex)", "Vinificație DOC Drăgășani", "Turism Balnear (Călimănești-Căciulata, Olănești)", "Agroturism Horezu"],
    keyIncentives: [
      "Granturi pentru crame moderne și turism viticol în Podgoria Drăgășani.",
      "Plăți pentru pajiști cu valoare naturală ridicată în Munții Căpățânii și Lotrului.",
      "Sprijin pentru pomicultură și depozite de fructe prin DR-16.",
    ],
    ancpiMonthlyAvg: "1.180 tranzacții",
    localFaqs: [
      { question: "Ce soiuri de vinuri sunt specifice în Vâlcea?", answer: "Podgoria Drăgășani este renumită pentru Crâmpoșie Selecționată, Negru de Drăgășani și Tămâioasă Românească." },
    ],
  },
  vrancea: {
    code: "VN",
    name: "Vrancea",
    region: "Sud-Est",
    capital: "Focșani",
    population: "335.000",
    activeImmCount: "13.200",
    adrName: "ADR Sud-Est",
    apiaCenter: "Centrul Județean APIA Vrancea — Str. Republicii nr. 64, Focșani",
    ojfirCenter: "OJFIR Vrancea — Str. Cuza Vodă nr. 8, Focșani",
    agriculturalSurfaceHa: "255.000 ha (150.000 ha arabil, 28.000 ha viță-de-vie — cel mai mare bazin viticol din țară, 75.000 ha pășuni/livezi)",
    topCrops: ["Viță-de-vie (Podgoriile Panciu, Odobești, Cotești - peste 20.000 ha)", "Grâu", "Porumb", "Livezi de meri și pruni"],
    topLivestock: ["Ovine (Bazinul Vrancei)", "Bovine carne/lapte", "Avicultură"],
    topIndustries: ["Vinificație & Spumante (Panciu, Beciul Domnesc Odobești)", "Confectii", "Industrie Alimentară", "Prelucrare Lemn"],
    keyIncentives: [
      "Cea mai mare alocare de fonduri pentru reconversie și restructurare viticolă din România.",
      "Granturi AFIR pentru modernizarea cramelor și tehnologiei de vinificație.",
      "Sprijin pentru cooperativele vitivinicole vrâncene.",
    ],
    ancpiMonthlyAvg: "1.210 tranzacții",
    localFaqs: [
      { question: "Cât reprezintă viticultura din Vrancea la nivel național?", answer: "Județul Vrancea deține circa 15% din întreaga suprafață viticolă a României, fiind capitala vinului autohton prin podgoriile Panciu, Odobești și Cotești." },
    ],
  },
};

export function getCountyProfile(slugOrName: string): CountyIntelligenceProfile {
  const decoded = decodeURIComponent(slugOrName).toLowerCase().trim()
    .normalize("NFD").replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]/g, "-");

  const cleanKey = decoded.replace(/-+/g, "-").replace(/^-|-$/g, "");
  
  if (countyProfilesCatalog[cleanKey]) {
    return countyProfilesCatalog[cleanKey];
  }

  // Check matching by name without diacritics
  const found = Object.values(countyProfilesCatalog).find((c) => {
    const cNorm = c.name.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "");
    return cNorm === cleanKey || c.code.toLowerCase() === cleanKey;
  });
  if (found) return found;

  const rawDecoded = decodeURIComponent(slugOrName);
  const formattedName = rawDecoded.charAt(0).toUpperCase() + rawDecoded.slice(1);

  return {
    code: rawDecoded.substring(0, 2).toUpperCase(),
    name: formattedName,
    region: "Național",
    capital: `Municipiul ${formattedName}`,
    population: "Sute de mii de locuitori",
    activeImmCount: "Zeci de mii de firme",
    adrName: "Agenția pentru Dezvoltare Regională",
    apiaCenter: `Centrul Județean APIA ${formattedName}`,
    ojfirCenter: `OJFIR ${formattedName}`,
    agriculturalSurfaceHa: "Sute de mii de hectare teren agricol",
    topCrops: ["Cereale de câmp", "Plante uleioase", "Pajiști permanente"],
    topLivestock: ["Bovine", "Ovine", "Porcine", "Păsări"],
    topIndustries: ["Agricultură", "Comerț", "Producție", "Servicii"],
    keyIncentives: ["Sprijin de bază BISS", "Eco-scheme APIA", "Granturi AFIR pentru tineri fermieri"],
    ancpiMonthlyAvg: "Peste 1.000 tranzacții",
    localFaqs: [
      { question: `Unde se depun cererile de subvenție în județul ${formattedName}?`, answer: `La Centrul Județean APIA ${formattedName} sau online prin aplicația IPA Online.` },
    ],
  };
}

export function getAllCounties(): CountyIntelligenceProfile[] {
  return Object.values(countyProfilesCatalog);
}
