export type FundingStatus = "Deschis" | "În curând" | "Închis" | "Suspendat" | "Permanent";

export type CompanyAge = "Nou înființată" | "Peste 1 an" | "Peste 2 ani" | "Peste 3 ani" | "Orice vechime";
export type CompanySize = "Microîntreprindere" | "Întreprindere mică" | "Întreprindere mijlocie" | "IMM" | "Întreprindere mare" | "Fermă individuală" | "Toate mărimile";
export type BusinessType = "SRL" | "PFA" | "II" | "IF" | "Fermă" | "Cooperativă" | "Grup Producători" | "OUAI" | "Persoană Fizică" | "Toate formele";

export type TimelineStep = {
  label: string;
  date: string;
};

export type FAQ = {
  question: string;
  answer: string;
};

export type FundingProgram = {
  slug: string;
  title: string;
  summary: string;
  status: FundingStatus;
  deadline: string;
  maxFundingRon: number;
  maxFundingEur?: number;
  minFundingRon?: number;
  source: string;
  sourceCategory: "APIA" | "AFIR" | "MADR" | "MIPE" | "ADR" | "AFM" | "PNRR" | "Minister";
  authorityCode?: string;
  verifiedStatus?: "OFICIAL" | "SURSĂ OFICIALĂ" | "PUBLIC" | "INDICATIV";
  businessTypes: string[];
  industries: string[];
  counties: string[];
  companyAge: CompanyAge;
  companySize: CompanySize;
  eligibility: string[];
  eligibleExpenses?: string[];
  ineligibleExpenses?: string[];
  documents: string[];
  cofinancing: string;
  supportIntensity?: string;
  officialUrl: string;
  timeline: TimelineStep[];
  faqs: FAQ[];
  relatedLegislation?: string[];
  relatedNews?: string[];
};

export const filterOptions = {
  business: [
    "Toate formele",
    "Persoană Fizică",
    "PFA",
    "II",
    "IF",
    "SRL",
    "Fermă",
    "Cooperativă",
    "Grup Producători",
    "OUAI",
  ],
  industry: [
    "Toate domeniile",
    "Cultura Plantelor & Arabil",
    "Zootehnie Bovine",
    "Zootehnie Ovine & Caprine",
    "Apicultură",
    "Pomicultură & Livezi",
    "Viticultură & Vinificație",
    "Legumicultură & Sere",
    "Agricultură Ecologică",
    "Irigații & Hidroameliorații",
    "Utilaje & Mecanizare",
    "Tineri Fermieri",
    "Procesare Alimentară",
    "Depozitare & Silozuri",
    "IT & Digitalizare",
    "Energie Verde & Mediu",
  ],
  county: [
    "Toate județele",
    "Național",
    "Alba", "Arad", "Argeș", "Bacău", "Bihor", "Bistrița-Năsăud", "Botoșani", "Brașov", "Brăila", "București",
    "Buzău", "Caraș-Severin", "Călărași", "Cluj", "Constanța", "Covasna", "Dâmbovița", "Dolj", "Galați", "Giurgiu",
    "Gorj", "Harghita", "Hunedoara", "Ialomița", "Iași", "Ilfov", "Maramureș", "Mehedinți", "Mureș", "Neamț",
    "Olt", "Prahova", "Satu Mare", "Sălaj", "Sibiu", "Suceava", "Teleorman", "Timiș", "Tulcea", "Vaslui", "Vâlcea", "Vrancea"
  ],
  companyAge: ["Orice vechime", "Nou înființată", "Peste 1 an", "Peste 2 ani", "Peste 3 ani"],
  companySize: ["Toate mărimile", "Fermă individuală", "Microîntreprindere", "Întreprindere mică", "Întreprindere mijlocie", "IMM", "Întreprindere mare"],
  sourceCategory: ["Toate sursele", "APIA", "AFIR", "MADR", "MIPE", "ADR", "AFM", "PNRR"],
  status: ["Toate statusurile", "Deschis", "În curând", "Închis", "Suspendat", "Permanent"],
};

export const FUNDING_PROGRAMS: FundingProgram[] = [
  {
    slug: "apia-biss-pd-01",
    title: "APIA PD-01: Sprijinul de Bază pentru Venit în Vederea Sustenabilității (BISS)",
    summary: "Plata directă decuplată de bază acordată tuturor fermierilor activi care exploatează legal o suprafață agricolă de minimum 1 hectar teren arabil, pășune sau culturi permanente.",
    status: "Deschis",
    deadline: "2026-06-15",
    maxFundingRon: 480000,
    maxFundingEur: 96470,
    minFundingRon: 480,
    source: "Agenția de Plăți și Intervenție pentru Agricultură (APIA)",
    sourceCategory: "APIA",
    authorityCode: "APIA-PD01",
    verifiedStatus: "OFICIAL",
    businessTypes: ["Persoană Fizică", "PFA", "II", "IF", "SRL", "Cooperativă"],
    industries: ["Cultura Plantelor & Arabil", "Zootehnie Bovine", "Zootehnie Ovine & Caprine", "Pomicultură & Livezi", "Viticultură & Vinificație"],
    counties: ["Național"],
    companyAge: "Orice vechime",
    companySize: "Toate mărimile",
    eligibility: [
      "Fermier activ înregistrat la APIA cu cod unic de identificare fermier.",
      "Exploatație de minimum 1 hectar, cu parcele agricole de cel puțin 0,3 hectare (0,1 ha pentru livezi, vii, pepiniere, solarii).",
      "Deținerea documentelor valabile de utilizare a terenului (titlu proprietate, contract arendare legal încheiat și înregistrat la primărie).",
      "Respectarea normelor de condiționalitate BGAO (Bunele Condiții Agricole și de Mediu) pe întreaga fermă.",
    ],
    eligibleExpenses: ["Sprijin forfetar direct pe suprafață (plată directă decuplată de producție)."],
    documents: [
      "Cerere unică de plată completată online prin aplicația IPA Online",
      "Adeverință emisă de Primărie conform înscrisurilor din Registrul Agricol",
      "Copie act identitate titular / CUI societate",
      "Documente justificative privind utilizarea legală a terenului (contracte arendare, extras CF)",
    ],
    cofinancing: "0% — Sprijin 100% nerambursabil FEGA (Fondul European de Garantare Agricolă).",
    supportIntensity: "100% sprijin direct",
    officialUrl: "https://apia.org.ro/directia-plati-directe/",
    timeline: [
      { label: "Depunere fără penalități", date: "4 Martie – 15 Mai 2026" },
      { label: "Depunere cu penalități de întârziere (1%/zi)", date: "16 Mai – 15 Iunie 2026" },
      { label: "Plata avansului (70%)", date: "16 Octombrie – 30 Noiembrie 2026" },
      { label: "Plata finală (sold)", date: "2 Decembrie 2026 – 30 Iunie 2027" },
    ],
    faqs: [
      {
        question: "Cât este cuantumul BISS pe hectar?",
        answer: "Cuantumul orientativ stabilit prin Planul Strategic PAC 2023–2027 este de circa 96,47 EUR/hectar/an, putând fi ajustat anual în funcție de suprafața totală eligibilă determinată la nivel național.",
      },
      {
        question: "Pot depune cererea dacă am contractul de arendă încheiat pe 1 an?",
        answer: "Da, cu condiția ca contractul de arendare să fie valabil la data depunerii cererii și să fie înregistrat la consiliul local / primărie conform Codului Civil.",
      },
    ],
    relatedLegislation: ["ordin-madr-80-2023-criterii-eligibilitate-pac", "hg-1571-2022-stabilire-cadrul-general-plati-directe"],
    relatedNews: ["campanie-depunere-cereri-plata-apia-2026", "calendar-plati-avans-apia-fega-feadr"],
  },
  {
    slug: "apia-criss-pd-02",
    title: "APIA PD-02: Sprijinul Redistributiv Complementar pentru Venit (CRISS)",
    summary: "Plată directă suplimentară acordată fermelor mici și mijlocii pentru primele 50 de hectare eligibile, stimulând consolidarea exploatațiilor agricole de familie.",
    status: "Deschis",
    deadline: "2026-06-15",
    maxFundingRon: 140000,
    maxFundingEur: 28000,
    minFundingRon: 250,
    source: "Agenția de Plăți și Intervenție pentru Agricultură (APIA)",
    sourceCategory: "APIA",
    authorityCode: "APIA-PD02",
    verifiedStatus: "OFICIAL",
    businessTypes: ["Persoană Fizică", "PFA", "II", "IF", "SRL"],
    industries: ["Cultura Plantelor & Arabil", "Zootehnie Bovine", "Zootehnie Ovine & Caprine", "Pomicultură & Livezi"],
    counties: ["Național"],
    companyAge: "Orice vechime",
    companySize: "Fermă individuală",
    eligibility: [
      "Exploatație agricolă cu suprafață determinată cuprinsă între 1,01 ha și maximum 50 ha.",
      "Beneficiar al schemei de bază BISS (PD-01).",
      "Nu se acordă fermelor create artificial prin fragmentarea exploatațiilor mari exclusiv în scopul obținerii sprijinului CRISS.",
    ],
    documents: [
      "Se bifează automat în cererea unică de plată IPA Online odată cu solicitarea BISS",
      "Adeverință Registru Agricol",
    ],
    cofinancing: "0% — 100% nerambursabil din FEGA.",
    supportIntensity: "100% sprijin direct",
    officialUrl: "https://apia.org.ro/directia-plati-directe/",
    timeline: [
      { label: "Campanie depunere cereri", date: "4 Martie – 15 Iunie 2026" },
      { label: "Plata avans 70%", date: "16 Octombrie – 30 Noiembrie 2026" },
    ],
    faqs: [
      {
        question: "Cât se plătește în plus pe hectar prin CRISS?",
        answer: "Cuantumul orientativ este de circa 50 – 56 EUR/hectar pentru fiecare hectar cuprins între 1 și 50 ha ale exploatației.",
      },
    ],
    relatedLegislation: ["ordin-madr-80-2023-criterii-eligibilitate-pac"],
  },
  {
    slug: "apia-tineri-fermieri-cis-yf-pd-03",
    title: "APIA PD-03: Sprijin Complementar pentru Venit pentru Tinerii Fermieri (CIS-YF)",
    summary: "Plată directă anuală suplimentară pe hectar acordată tinerilor fermieri de până la 40 de ani, pentru o perioadă de maximum 5 ani consecutivi de la instalare.",
    status: "Deschis",
    deadline: "2026-06-15",
    maxFundingRon: 115000,
    maxFundingEur: 23000,
    minFundingRon: 230,
    source: "Agenția de Plăți și Intervenție pentru Agricultură (APIA)",
    sourceCategory: "APIA",
    authorityCode: "APIA-PD03",
    verifiedStatus: "OFICIAL",
    businessTypes: ["PFA", "II", "IF", "SRL"],
    industries: ["Tineri Fermieri", "Cultura Plantelor & Arabil", "Zootehnie Bovine", "Pomicultură & Livezi"],
    counties: ["Național"],
    companyAge: "Nou înființată",
    companySize: "Microîntreprindere",
    eligibility: [
      "Vârsta de până la 40 de ani împliniți în anul primei depuneri a cererii de plată.",
      "Să fie șef unic de exploatație sau să dețină controlul efectiv în societatea comercială agricolă.",
      "Document de calificare profesională în agricultură (diplomă de studii medii/superioare agricole sau certificat curs calificare min. 360 ore).",
      "Suprafața maximă eligibilă pentru plata suplimentară CIS-YF: 50 hectare/fermă.",
    ],
    documents: [
      "Diplomă de studii agricole sau certificat de formare profesională",
      "Act constitutiv / Hotărâre AGA privind exercitarea controlului decizional",
      "Cerere unică de plată IPA Online",
    ],
    cofinancing: "0% — 100% nerambursabil.",
    supportIntensity: "100% sprijin direct",
    officialUrl: "https://apia.org.ro/directia-plati-directe/",
    timeline: [
      { label: "Perioadă depunere cerere", date: "Martie – Iunie 2026" },
      { label: "Autorizare la plată", date: "Octombrie 2026 – Februarie 2027" },
    ],
    faqs: [
      {
        question: "Câți ani pot beneficia de CIS-YF?",
        answer: "Sprijinul se acordă pentru o perioadă de maximum 5 ani consecutivi, începând de la prima cerere eligibilă depusă după instalarea ca tânăr fermier.",
      },
    ],
    relatedLegislation: ["ordin-madr-80-2023-criterii-eligibilitate-pac"],
  },
  {
    slug: "apia-eco-schema-teren-arabil-pd-04",
    title: "APIA PD-04: Eco-Schema — Practici Benefice pentru Mediu pe Terenul Arabil",
    summary: "Eco-schemă voluntară cu plată suplimentară pe hectar pentru fermierii care alocă suprafețe culturilor fixatoare de azot, mențin covor vegetal pe timp de iarnă și diversifică asolamentul.",
    status: "Deschis",
    deadline: "2026-06-15",
    maxFundingRon: 365000,
    maxFundingEur: 73000,
    minFundingRon: 365,
    source: "Agenția de Plăți și Intervenție pentru Agricultură (APIA)",
    sourceCategory: "APIA",
    authorityCode: "APIA-PD04",
    verifiedStatus: "OFICIAL",
    businessTypes: ["Persoană Fizică", "PFA", "II", "IF", "SRL", "Cooperativă"],
    industries: ["Cultura Plantelor & Arabil", "Agricultură Ecologică"],
    counties: ["Național"],
    companyAge: "Orice vechime",
    companySize: "Toate mărimile",
    eligibility: [
      "Exploatație arabilă de minimum 10,01 ha (sau 1–10 ha pentru pachetul simplificat de diversificare).",
      "Cultivarea a cel puțin 10% din terenul arabil cu plante leguminoase fixatoare de azot (lucernă, soia, mazăre, fasole, trifoi, năut, bob).",
      "Menținerea acoperirii solului cu miriște, culturi secundare sau culturi de toamnă pe minimum 85% din arabil în perioada critică (15 iunie – 15 octombrie).",
    ],
    documents: [
      "Cerere unică de plată cu opțiune bifată pentru PD-04",
      "Registru de evidență a tratamentelor fitosanitare și asolamentului",
      "Facturi de achiziție sămânță certificată pentru culturile leguminoase",
    ],
    cofinancing: "0% — Sprijin 100% FEGA.",
    supportIntensity: "100% sprijin suplimentar",
    officialUrl: "https://apia.org.ro/directia-plati-directe/",
    timeline: [
      { label: "Depunere cerere", date: "4 Martie – 15 Iunie 2026" },
      { label: "Verificări administrative și teledetecție", date: "Iulie – Septembrie 2026" },
      { label: "Plată avans", date: "Octombrie 2026" },
    ],
    faqs: [
      {
        question: "Cât este cuantumul plății pentru eco-schema PD-04?",
        answer: "Cuantumul orientativ anual este de aproximativ 73,00 EUR/hectar, adițional plății BISS și CRISS.",
      },
    ],
    relatedLegislation: ["ordin-madr-106-2024-derogari-gaec", "ordin-madr-80-2023-criterii-eligibilitate-pac"],
  },
  {
    slug: "apia-sprijin-cuplat-vaci-lapte-pd-21",
    title: "APIA PD-21: Sprijin Cuplat pentru Venit — Vaci de Lapte (SCZ)",
    summary: "Subvenție directă pe cap de animal destinată crescătorilor de vaci de lapte pentru susținerea producției autohtone de lapte conform și ameliorarea genetică a efectivelor.",
    status: "Deschis",
    deadline: "2026-06-15",
    maxFundingRon: 422500,
    maxFundingEur: 84500,
    minFundingRon: 16900,
    source: "Agenția de Plăți și Intervenție pentru Agricultură (APIA)",
    sourceCategory: "APIA",
    authorityCode: "APIA-PD21",
    verifiedStatus: "OFICIAL",
    businessTypes: ["PFA", "II", "IF", "SRL", "Cooperativă"],
    industries: ["Zootehnie Bovine"],
    counties: ["Național"],
    companyAge: "Orice vechime",
    companySize: "Toate mărimile",
    eligibility: [
      "Efectiv de minimum 10 capete și maximum 250 capete vaci de lapte (între 5 și 250 capete în zona montană).",
      "Vârsta animalului: maximum 10 ani la data limită de depunere a cererii.",
      "Vaca de lapte trebuie să fi fătat cel puțin o dată și să fie înregistrată în Baza Națională de Date (BND).",
      "Animale înscrise în Registrul Genealogic al rasei (secțiunea principală sau suplimentară) sau în Controlul Oficial al Performanțelor Producției de Lapte (COP).",
      "Dovada livrării/vânzării directe a unei cantități minime de lapte de 3.000 kg/cap/an (2.000 kg în zona montană).",
      "Perioadă de retenție în fermă: minimum 4 luni de la data limită de depunere.",
    ],
    documents: [
      "Adeverință eliberată de asociația acreditată care conduce Registrul Genealogic sau efectuează COP",
      "Copie facturi fiscale de livrare a laptelui către prim-cumpărător autorizat sau file din carnetul de comercializare",
      "Raport extras din Baza Națională de Date ANSVSA",
    ],
    cofinancing: "0% — 100% nerambursabil.",
    supportIntensity: "100% sprijin direct",
    officialUrl: "https://apia.org.ro/directia-plati-directe/",
    timeline: [
      { label: "Depunere cerere", date: "4 Martie – 15 Iunie 2026" },
      { label: "Perioadă de retenție obligatorie", date: "16 Iunie – 15 Octombrie 2026" },
      { label: "Plată", date: "Decembrie 2026 – Iunie 2027" },
    ],
    faqs: [
      {
        question: "Cât este sprijinul pe cap de vacă de lapte?",
        answer: "Cuantumul unitar planificat este de circa 338,00 EUR/cap de animal eligibil pe an.",
      },
    ],
    relatedLegislation: ["ordin-madr-80-2023-criterii-eligibilitate-pac"],
  },
  {
    slug: "apia-sprijin-cuplat-taurine-carne-pd-22",
    title: "APIA PD-22: Sprijin Cuplat pentru Venit — Taurine de Carne (SCZ)",
    summary: "Subvenție pe cap de animal acordată fermierilor care cresc rase specializate de taurine de carne și metișii acestora, inclusiv tineret taurin destinat îngrășării și sacrificării.",
    status: "Deschis",
    deadline: "2026-06-15",
    maxFundingRon: 348000,
    maxFundingEur: 69750,
    minFundingRon: 13950,
    source: "Agenția de Plăți și Intervenție pentru Agricultură (APIA)",
    sourceCategory: "APIA",
    authorityCode: "APIA-PD22",
    verifiedStatus: "OFICIAL",
    businessTypes: ["PFA", "II", "IF", "SRL", "Fermă"],
    industries: ["Zootehnie Bovine"],
    counties: ["Național"],
    companyAge: "Orice vechime",
    companySize: "Toate mărimile",
    eligibility: [
      "Efectiv de minimum 10 capete și maximum 250 capete taurine din rase de carne (5–250 capete în zona montană).",
      "Vaci din rase de carne sau metise cu rase de carne, tauri de reproducție autorizați sau tineret taurin între 8 și 32 luni.",
      "Înscriere în Registrul Genealogic al rasei de carne (secțiunea principală sau suplimentară).",
      "Respectarea perioadei de retenție de minimum 4 luni de la data limită de depunere a cererii.",
    ],
    documents: [
      "Adeverință Registru Genealogic eliberată de asociația de profil acreditată",
      "Copie pașapoarte bovine și formular de mișcare SNIIA",
      "Factură de livrare abator sau documente de sacrificare (pentru tineret)",
    ],
    cofinancing: "0% — Sprijin 100% FEGA.",
    supportIntensity: "100% sprijin direct",
    officialUrl: "https://apia.org.ro/directia-plati-directe/",
    timeline: [
      { label: "Depunere cerere", date: "4 Martie – 15 Iunie 2026" },
      { label: "Plată finală", date: "Ianuarie – Iunie 2027" },
    ],
    faqs: [
      {
        question: "Cât este cuantumul pentru taurinele de carne?",
        answer: "Cuantumul orientativ anual este de circa 279,00 EUR/cap de animal eligibil.",
      },
    ],
    relatedLegislation: ["ordin-madr-80-2023-criterii-eligibilitate-pac"],
  },
  {
    slug: "apia-sprijin-cuplat-ovine-caprine-pd-24",
    title: "APIA PD-24: Sprijin Cuplat pentru Venit — Ovine și Caprine (SCZ)",
    summary: "Sprijin financiar anual pe cap de femelă ovină sau caprină menținută în exploatație, înscrisă în Registrul Genealogic și deservită de berbeci/țapi cu certificate de origine.",
    status: "Deschis",
    deadline: "2026-06-15",
    maxFundingRon: 37500,
    maxFundingEur: 7500,
    minFundingRon: 1875,
    source: "Agenția de Plăți și Intervenție pentru Agricultură (APIA)",
    sourceCategory: "APIA",
    authorityCode: "APIA-PD24",
    verifiedStatus: "OFICIAL",
    businessTypes: ["Persoană Fizică", "PFA", "II", "IF", "SRL"],
    industries: ["Zootehnie Ovine & Caprine"],
    counties: ["Național"],
    companyAge: "Orice vechime",
    companySize: "Fermă individuală",
    eligibility: [
      "Efectiv cuprins între minimum 150 și maximum 500 capete femele ovine/caprine (între 60 și 500 capete în zona montană).",
      "Vârsta animalelor: minimum 1 an la data de 31 decembrie a anului de cerere și maximum 8 ani (pentru oi) / 6 ani (pentru capre).",
      "Înscrierea femelelor în Registrul Genealogic al rasei.",
      "Raport obligatoriu de berbeci: minimum 1 berbec cu certificat de origine la fiecare 35 de femele ovine eligibile.",
      "Perioadă de retenție: minimum 100 de zile în exploatație.",
    ],
    documents: [
      "Adeverință Registru Genealogic eliberată de asociația acreditată",
      "Certificate de origine pentru berbecii/țapii autorizați de reproducție",
      "Formular F2 de mișcare și actualizare SNIIA",
    ],
    cofinancing: "0% — Finanțare 100% FEGA.",
    supportIntensity: "100% sprijin direct",
    officialUrl: "https://apia.org.ro/directia-plati-directe/",
    timeline: [
      { label: "Depunere cerere", date: "4 Martie – 15 Iunie 2026" },
      { label: "Perioadă retenție (100 zile)", date: "16 Iunie – 23 Septembrie 2026" },
      { label: "Plată", date: "Decembrie 2026 – Mai 2027" },
    ],
    faqs: [
      {
        question: "Cât este subvenția pe cap de oaie prin PD-24?",
        answer: "Cuantumul orientativ este de circa 12,50 – 15,00 EUR/cap de femelă ovină/caprină eligibilă, la care se adaugă plata ANTZ 9.",
      },
    ],
    relatedLegislation: ["ordin-madr-80-2023-criterii-eligibilitate-pac"],
  },
  {
    slug: "apia-sprijin-cuplat-soia-pd-09",
    title: "APIA PD-09: Sprijin Cuplat pentru Venit — Soia",
    summary: "Subvenție pe hectar destinată fermierilor care cultivă soia boabe, pentru stimularea producției autohtone de proteine vegetale și reducerea dependenței de importuri furajere.",
    status: "Deschis",
    deadline: "2026-06-15",
    maxFundingRon: 750000,
    maxFundingEur: 150000,
    minFundingRon: 750,
    source: "Agenția de Plăți și Intervenție pentru Agricultură (APIA)",
    sourceCategory: "APIA",
    authorityCode: "APIA-PD09",
    verifiedStatus: "OFICIAL",
    businessTypes: ["PFA", "II", "IF", "SRL", "Cooperativă"],
    industries: ["Cultura Plantelor & Arabil"],
    counties: ["Național"],
    companyAge: "Orice vechime",
    companySize: "Toate mărimile",
    eligibility: [
      "Cultivarea soiei pe o suprafață minimă de 1 ha, parcelă minimă de 0,3 ha.",
      "Utilizarea obligatorie de sămânță certificată oficial (etichetă oficială albastră/roșie + factură fiscală).",
      "Dovada obținerii și comercializării unei producții minime de 1.300 kg soia boabe/hectar (sau utilizarea în furajarea propriilor animale).",
    ],
    documents: [
      "Factură fiscală de achiziție a seminței certificate și etichetele oficiale",
      "Facturi fiscale de vânzare a producției minime de 1.300 kg/ha sau fișă consum furaje",
      "Dovada contractului cu un prim-cumpărător/procesator autorizat",
    ],
    cofinancing: "0% — FEGA.",
    supportIntensity: "100% sprijin direct",
    officialUrl: "https://apia.org.ro/directia-plati-directe/",
    timeline: [
      { label: "Depunere cerere", date: "Martie – Iunie 2026" },
      { label: "Depunere documente justificative producție", date: "Până la 15 Ianuarie 2027" },
    ],
    faqs: [
      {
        question: "Cât este cuantumul sprijinului cuplat pentru soia?",
        answer: "Cuantumul orientativ anual este de aproximativ 150,00 EUR/hectar, adițional schemei de bază BISS și CRISS.",
      },
    ],
    relatedLegislation: ["ordin-madr-80-2023-criterii-eligibilitate-pac"],
  },
  {
    slug: "apia-sprijin-cuplat-lucerna-pd-10",
    title: "APIA PD-10: Sprijin Cuplat pentru Venit — Lucernă",
    summary: "Plată cuplată pe hectar acordată cultivatorilor de lucernă destinate producției de fân, firi sau pelete furajere de înaltă valoare proteică.",
    status: "Deschis",
    deadline: "2026-06-15",
    maxFundingRon: 505000,
    maxFundingEur: 101000,
    minFundingRon: 505,
    source: "Agenția de Plăți și Intervenție pentru Agricultură (APIA)",
    sourceCategory: "APIA",
    authorityCode: "APIA-PD10",
    verifiedStatus: "OFICIAL",
    businessTypes: ["Persoană Fizică", "PFA", "II", "IF", "SRL"],
    industries: ["Cultura Plantelor & Arabil", "Zootehnie Bovine"],
    counties: ["Național"],
    companyAge: "Orice vechime",
    companySize: "Toate mărimile",
    eligibility: [
      "Suprafață cultivată cu lucernă de minimum 1 ha.",
      "Utilizarea seminței certificate la înființarea culturii.",
      "Dovada obținerii unei producții minime de 15 tone/ha masă verde (sau 3,75 tone/ha fân) pe an.",
      "Comercializarea producției sau consumul în propria fermă zootehnică înregistrată la APIA/ANSVSA.",
    ],
    documents: [
      "Factură fiscală de achiziție a seminței certificate",
      "Facturi de vânzare a lucernei sau fișă de magazie și consum furajer în ferma proprie",
    ],
    cofinancing: "0% — Sprijin 100% FEGA.",
    supportIntensity: "100% sprijin direct",
    officialUrl: "https://apia.org.ro/directia-plati-directe/",
    timeline: [
      { label: "Depunere cerere", date: "Martie – Iunie 2026" },
      { label: "Prezentare dovezi producție", date: "Până la 15 Ianuarie 2027" },
    ],
    faqs: [
      {
        question: "Cât este sprijinul pe hectar pentru lucernă?",
        answer: "Cuantumul orientativ anual este de circa 101,00 EUR/hectar.",
      },
    ],
    relatedLegislation: ["ordin-madr-80-2023-criterii-eligibilitate-pac"],
  },
  {
    slug: "madr-ajutor-stat-motorina-agricultura",
    title: "MADR: Ajutor de Stat pentru Reducerea Accizei la Motorina Utilizată în Agricultură",
    summary: "Rambursare trimestrială a diferenței dintre cota standard a accizei și cota redusă pentru motorina utilizată la efectuarea lucrărilor mecanizate în agricultură și zootehnie.",
    status: "Permanent",
    deadline: "2026-10-31",
    maxFundingRon: 2500000,
    maxFundingEur: 500000,
    minFundingRon: 1000,
    source: "Ministerul Agriculturii și Dezvoltării Rurale prin APIA",
    sourceCategory: "MADR",
    authorityCode: "MADR-HG818",
    verifiedStatus: "OFICIAL",
    businessTypes: ["PFA", "II", "IF", "SRL", "Fermă", "Cooperativă"],
    industries: ["Cultura Plantelor & Arabil", "Zootehnie Bovine", "Zootehnie Ovine & Caprine", "Pomicultură & Livezi", "Utilaje & Mecanizare"],
    counties: ["Național"],
    companyAge: "Orice vechime",
    companySize: "Toate mărimile",
    eligibility: [
      "Fermieri înregistrați în Registrul Unic de Identificare (RUI) al APIA cu cerere de acord prealabil aprobată.",
      "Deținerea în proprietate sau comodat a utilajelor agricole autopropulsate înmatriculate/înregistrate.",
      "Achiziționarea motorinei exclusiv de la distribuitori autorizați, însoțită de facturi fiscale și bonuri fiscale cu CUI.",
      "Respectarea normelor de consum mediu de motorină pe culturi și specii de animale stabilite prin ordin comun MADR/MFP.",
    ],
    documents: [
      "Cerere de acord prealabil pentru finanțare depusă anual în luna decembrie",
      "Cereri trimestriale de plată depuse până la sfârșitul lunii următoare trimestrului",
      "Copii facturi fiscale de achiziție motorină emise pe CUI-ul beneficiarului",
      "Registru de evidență a lucrărilor agricole mecanizate pe parcele",
    ],
    cofinancing: "0% — Rambursare 100% a diferenței de acciză din bugetul de stat.",
    supportIntensity: "1,746 lei/litru subvenție rambursată",
    officialUrl: "https://apia.org.ro/directia-masuri-de-piata/ajutoare-de-stat/",
    timeline: [
      { label: "Trimestrul I (lucrări ian–mar)", date: "Depunere: 1 – 30 Aprilie" },
      { label: "Trimestrul II (lucrări apr–iun)", date: "Depunere: 1 – 31 Iulie" },
      { label: "Trimestrul III (lucrări iul–sep)", date: "Depunere: 1 – 31 Octombrie" },
      { label: "Trimestrul IV (lucrări oct–dec)", date: "Depunere: 1 – 31 Ianuarie" },
    ],
    faqs: [
      {
        question: "Cât este valoarea subvenției la motorină?",
        answer: "Valoarea ajutorului este de circa 1,746 lei/litru de motorină consumată conform baremelor tehnice pe hectar sau cap de animal.",
      },
    ],
    relatedLegislation: ["hg-1571-2022-stabilire-cadrul-general-plati-directe"],
    relatedNews: ["plata-ajutor-stat-motorina-trimestrial"],
  },
  {
    slug: "afir-dr-30-instalare-tineri-fermieri",
    title: "AFIR DR-30: Instalarea Tinerilor Fermieri în Mediul Rural",
    summary: "Grant 100% nerambursabil de 70.000 EUR acordat tinerilor fermieri sub 40 de ani care preiau sau înființează pentru prima dată o exploatație agricolă viabilă.",
    status: "În curând",
    deadline: "2026-11-30",
    maxFundingRon: 350000,
    maxFundingEur: 70000,
    minFundingRon: 350000,
    source: "Agenția pentru Finanțarea Investițiilor Rurale (AFIR)",
    sourceCategory: "AFIR",
    authorityCode: "AFIR-DR30",
    verifiedStatus: "OFICIAL",
    businessTypes: ["PFA", "II", "SRL"],
    industries: ["Tineri Fermieri", "Cultura Plantelor & Arabil", "Zootehnie Bovine", "Zootehnie Ovine & Caprine", "Pomicultură & Livezi", "Legumicultură & Sere"],
    counties: ["Național"],
    companyAge: "Nou înființată",
    companySize: "Microîntreprindere",
    eligibility: [
      "Vârsta de maximum 40 de ani la momentul depunerii proiectului (40 ani și 364 zile).",
      "Înregistrat ca șef unic de exploatație agricolă la ONRC și APIA/ANSVSA cu cel mult 24 de luni înainte de depunerea cererii.",
      "Dimensiune economică a exploatației între 8.000 SO și 100.000 SO (minimum 4.000 SO în zona montană).",
      "Competențe profesionale atestate prin diplomă sau certificat recunoscut ANC.",
      "Plan de afaceri realist pe o perioadă de maximum 3 ani.",
    ],
    eligibleExpenses: [
      "Achiziție utilaje agricole și echipamente noi",
      "Înființare plantații pomicole/viticole, solarii, adăposturi animale",
      "Achiziție animale de reproducție și material biologic",
      "Cumpărare teren agricol (în limita a 10% din grant)",
      "Digitalizare și sisteme de energie regenerabilă la nivel de fermă",
    ],
    documents: [
      "Plan de afaceri completat pe formularul tip AFIR",
      "Certificat constatator ONRC și act constitutiv",
      "Documente de proprietate sau contracte arendare teren pe minimum 10 ani",
      "Diplomă de calificare profesională",
    ],
    cofinancing: "0% — Sprijin forfetar 100% nerambursabil acordat în 2 tranșe (75% la semnare, 25% la final).",
    supportIntensity: "100% grant forfetar",
    officialUrl: "https://www.afir.ro",
    timeline: [
      { label: "Publicare Ghid Solicitant Final", date: "August 2026" },
      { label: "Deschidere sesiune depunere online", date: "Octombrie – Noiembrie 2026" },
      { label: "Evaluare și selecție dosare", date: "Decembrie 2026 – Ianuarie 2027" },
    ],
    faqs: [
      {
        question: "Cât este grantul și cum se plătește?",
        answer: "Grantul este de 70.000 EUR fix. Se plătește 75% (52.500 EUR) ca avans la semnarea contractului și 25% (17.500 EUR) la finalul implementării planului de afaceri.",
      },
      {
        question: "Este obligatoriu să domiciliez la sat?",
        answer: "Da, beneficiarul trebuie să aibă domiciliul stabil și sediul social în localitatea unde este situată exploatația agricolă.",
      },
    ],
    relatedLegislation: ["regulamentul-ue-2021-2115-pac", "ordin-madr-80-2023-criterii-eligibilitate-pac"],
    relatedNews: ["ghid-afir-instalare-tineri-fermieri-dr30"],
  },
  {
    slug: "afir-dr-14-investitii-ferme-de-familie",
    title: "AFIR DR-14: Investiții în Fermele de Mici Dimensiuni",
    summary: "Granturi nerambursabile de până la 50.000 EUR/proiect cu o intensitate a sprijinului public de până la 85% destinate dezvoltării și modernizării exploatațiilor agricole de mici dimensiuni (dimensiune economică între 4.000 SO și 11.999 SO).",
    status: "Deschis",
    deadline: "2026-10-31",
    maxFundingRon: 250000,
    maxFundingEur: 50000,
    minFundingRon: 25000,
    source: "Agenția pentru Finanțarea Investițiilor Rurale (AFIR)",
    sourceCategory: "AFIR",
    authorityCode: "AFIR-DR14",
    verifiedStatus: "OFICIAL",
    businessTypes: ["PFA", "II", "IF", "SRL"],
    industries: ["Cultura Plantelor & Arabil", "Utilaje & Mecanizare", "Zootehnie Bovine", "Pomicultură & Livezi", "Legumicultură & Solarii"],
    counties: ["Național"],
    companyAge: "Peste 1 an",
    companySize: "Microîntreprindere",
    eligibility: [
      "Exploatație agricolă cu dimensiune economică între 4.000 SO și 11.999 SO (Standard Output).",
      "Fermier activ înregistrat la APIA/Registrul Agricol cu istoric de producție de minimum 1 an.",
      "Exploatația și sediul profesional situate în mediul rural / periurban pe teritoriul României.",
      "Proiectul vizează una dintre cele 4 componente oficiale: Vegetal, Zootehnie, Legume/Cartofi sau Zone Montane.",
    ],
    eligibleExpenses: [
      "Achiziția de utilaje și echipamente agricole noi adaptate fermelor mici (tractoare de putere mică/medie conform suprafeței, semănători, cositori)",
      "Construcție / modernizare adăposturi de animale și spații de stocare de mici dimensiuni",
      "Solarii și spații protejate pentru legume și fructe",
      "Instalații de irigații la nivel de parcelă și sisteme de picurare",
      "Echipamente pentru procesare primară la nivelul fermei și panouri fotovoltaice pentru autoconsum",
    ],
    documents: [
      "Plan de afaceri simplificat / Memoriu justificativ întocmit conform machetei oficiale AFIR",
      "Oferte de preț din Baza de Date de Prețuri de Referință AFIR",
      "Bilanț contabil depus / Declarație unică ANAF pe anul precedent",
      "Adeverință APIA și extras din Registrul Agricol pentru atestarea suprafeței și efectivului",
    ],
    cofinancing: "15% cofinanțare privată obligatorie din valoarea cheltuielilor eligibile.",
    supportIntensity: "Până la 85% sprijin nerambursabil (15% contribuție proprie)",
    officialUrl: "https://www.afir.ro/domenii-de-interventie/detalii-si-anexe-dr-14",
    timeline: [
      { label: "Publicare Ghid Solicitant oficial", date: "August 2026" },
      { label: "Sesiune curentă de depunere proiecte", date: "01 Septembrie 2026 – 31 Octombrie 2026" },
    ],
    faqs: [
      {
        question: "Care este valoarea maximă a grantului nerambursabil prin DR-14?",
        answer: "Grantul maxim nerambursabil este de 50.000 EUR per proiect, acoperind până la 85% din totalul cheltuielilor eligibile.",
      },
      {
        question: "Cine poate aplica la DR-14?",
        answer: "Fermele mici având o dimensiune economică între 4.000 SO și 11.999 SO, înregistrate la APIA cu activitate de minimum 1 an.",
      },
      {
        question: "Pot achiziționa tractor prin DR-14?",
        answer: "Da, achiziția de tractoare și utilaje agricole este eligibilă dacă puterea este dimensionată proporțional cu Standard Output-ul exploatației conform grilei tehnice AFIR.",
      },
    ],
    relatedLegislation: ["regulamentul-ue-2021-2115-pac", "ordin-madr-80-2023-criterii-eligibilitate-pac"],
  },
  {
    slug: "afir-dr-15-investitii-exploatatii-agricole",
    title: "AFIR DR-15: Investiții în Exploatațiile Agricole din Sectorul Vegetal",
    summary: "Granturi mari de până la 1.500.000–3.000.000 EUR pentru modernizarea fermelor mari, construcția de silozuri, depozite climatizate, sisteme de condiționare și digitalizare avansată.",
    status: "Închis",
    deadline: "2026-12-31",
    maxFundingRon: 7500000,
    maxFundingEur: 1500000,
    minFundingRon: 500000,
    source: "Agenția pentru Finanțarea Investițiilor Rurale (AFIR)",
    sourceCategory: "AFIR",
    authorityCode: "AFIR-DR15",
    verifiedStatus: "OFICIAL",
    businessTypes: ["SRL", "Cooperativă", "Grup Producători"],
    industries: ["Cultura Plantelor & Arabil", "Depozitare & Silozuri", "Utilaje & Mecanizare"],
    counties: ["Național"],
    companyAge: "Peste 1 an",
    companySize: "IMM",
    eligibility: [
      "Dimensiune economică a fermei de minimum 12.000 SO.",
      "Viabilitate economică demonstrată pe baza situațiilor financiare din ultimii ani.",
      "Proiectul vizează creșterea valorii adăugate sau eficienței resurselor.",
    ],
    eligibleExpenses: [
      "Construcție baze silozuri, uscătoare de cereale, selectoare",
      "Construcție hale depozitare cereale, utilaje de mare capacitate",
      "Software de management integrat al fermei și agricultură de precizie",
    ],
    documents: [
      "Proiect Tehnic / Studiu de Fezabilitate complet conform HG 907/2016",
      "Acord de mediu emis de Agenția pentru Protecția Mediului (APM)",
      "Certificat de urbanism și autorizație de construire / avize utilități",
    ],
    cofinancing: "35%–50% cofinanțare proprie.",
    supportIntensity: "50% – 65% grant nerambursabil",
    officialUrl: "https://www.afir.ro",
    timeline: [
      { label: "Sesiune precedentă încheiată", date: "Evaluare proiecte în curs" },
      { label: "Sesiune nouă", date: "Calendar oficial în pregătire la MADR" },
    ],
    faqs: [
      {
        question: "Cât este valoarea maximă a sprijinului pentru cooperative?",
        answer: "Pentru cooperativele agricole și grupurile de producători, valoarea sprijinului nerambursabil poate ajunge până la 3.000.000 EUR per proiect.",
      },
    ],
    relatedLegislation: ["regulamentul-ue-2021-2115-pac"],
  },
  {
    slug: "afir-dr-20-investitii-sector-zootehnic",
    title: "AFIR DR-20: Investiții în Modernizarea Sectorului Zootehnic",
    summary: "Granturi de până la 2.000.000 EUR pentru construcția de grajduri moderne de bovine, ovine, suine și păsări, săli de muls robotizate, depozite de furaje și platforme de dejecții.",
    status: "În curând",
    deadline: "2026-12-15",
    maxFundingRon: 10000000,
    maxFundingEur: 2000000,
    minFundingRon: 500000,
    source: "Agenția pentru Finanțarea Investițiilor Rurale (AFIR)",
    sourceCategory: "AFIR",
    authorityCode: "AFIR-DR20",
    verifiedStatus: "OFICIAL",
    businessTypes: ["PFA", "II", "SRL", "Cooperativă"],
    industries: ["Zootehnie Bovine", "Zootehnie Ovine & Caprine"],
    counties: ["Național"],
    companyAge: "Orice vechime",
    companySize: "IMM",
    eligibility: [
      "Exploatație zootehnică autorizată sanitar-veterinar de DSVSA.",
      "Dimensiune economică minimă: 12.000 SO pentru bovine, 8.000 SO pentru ovine/caprine.",
      "Proiectul include obligatoriu măsuri de gestionare a dejecțiilor și conformitate cu Directiva Nitrați.",
    ],
    eligibleExpenses: [
      "Construcție și modernizare adăposturi de animale, maternități, tineret",
      "Săli de muls, roboți de muls, tancuri de răcire lapte",
      "Faze de stocare furaje, remorci tehnologice, utilaje de furajare",
      "Platforme betonate și lagune de stocare a gunoiului de grajd",
    ],
    documents: [
      "Studiu de Fezabilitate / DALI conform HG 907/2016",
      "Aviz sanitar-veterinar de conformitate emis de DSVSA",
      "Acord de mediu APM",
    ],
    cofinancing: "35%–50% cofinanțare privată.",
    supportIntensity: "50% – 65% nerambursabil",
    officialUrl: "https://www.afir.ro",
    timeline: [
      { label: "Ghid Solicitant Finalizat", date: "Septembrie 2026" },
      { label: "Deschidere sesiune depunere", date: "Octombrie – Decembrie 2026" },
    ],
    faqs: [
      {
        question: "Sunt eligibile utilajele de preparare a hranei?",
        answer: "Da, remorcile tehnologice de amestecat și distribuit furaje, morile de fermă și liniile automate de furajare sunt cheltuieli eligibile.",
      },
    ],
    relatedLegislation: ["regulamentul-ue-2021-2115-pac"],
  },
  {
    slug: "afir-dr-22-procesare-produse-agricole",
    title: "AFIR DR-22: Investiții în Procesarea și Condiționarea Produselor Agricole",
    summary: "Granturi de până la 3.000.000–10.000.000 EUR pentru crearea și modernizarea capacităților de procesare agroalimentară: abatoare, carmangerii, fabrici de lapte, panificație și sucuri.",
    status: "Închis",
    deadline: "2026-12-31",
    maxFundingRon: 15000000,
    maxFundingEur: 3000000,
    minFundingRon: 1000000,
    source: "Agenția pentru Finanțarea Investițiilor Rurale (AFIR)",
    sourceCategory: "AFIR",
    authorityCode: "AFIR-DR22",
    verifiedStatus: "OFICIAL",
    businessTypes: ["SRL", "Cooperativă"],
    industries: ["Procesare Alimentară", "Zootehnie Bovine", "Pomicultură & Livezi", "Legumicultură & Sere"],
    counties: ["Național"],
    companyAge: "Peste 1 an",
    companySize: "IMM",
    eligibility: [
      "Unitate de procesare conformă cu Anexa I la Tratatul de Funcționare al UE.",
      "Dovada că minimum 70% din materia primă procesată provine din producție autohtonă.",
      "Standarde înalte de biosecuritate și siguranță alimentară (HACCP/IFS).",
    ],
    eligibleExpenses: [
      "Linii tehnologice de prelucrare carne, lapte, fructe, legume, cereale",
      "Construcție hale de procesare și depozitare frigorifică",
      "Laboratoare de analiză a calității materiilor prime și produselor finite",
      "Mijloace de transport frigorific specializate",
    ],
    documents: [
      "Studiu de Fezabilitate cu analiză cost-beneficiu detaliată",
      "Bilanțuri contabile auditate pe ultimii 2 ani",
      "Autorizație de construire / Certificat de urbanism",
    ],
    cofinancing: "35%–50% cofinanțare privată.",
    supportIntensity: "50% – 65% nerambursabil",
    officialUrl: "https://www.afir.ro",
    timeline: [
      { label: "Sesiune apel încheiată", date: "Evaluare conformitate" },
      { label: "Realocare bugete", date: "Conform deciziei MADR" },
    ],
    faqs: [
      {
        question: "Se pot cumpăra autoutilitare frigorifice?",
        answer: "Da, autoutilitarele izoterme și frigorifice destinate exclusiv transportului materiei prime și produselor procesate sunt eligibile.",
      },
    ],
    relatedLegislation: ["regulamentul-ue-2021-2115-pac"],
  },
  {
    slug: "afir-dr-25-modernizare-irigatii-ouai",
    title: "AFIR DR-25: Modernizarea Infrastructurii Secundare de Irigații (OUAI)",
    summary: "Finanțare 100% nerambursabilă de până la 1.500.000 EUR per organizație de udători (OUAI/FOUAI) pentru reabilitarea stațiilor de pompare, hidrofoarelor și canalelor de aducțiune.",
    status: "Deschis",
    deadline: "2026-09-30",
    maxFundingRon: 7500000,
    maxFundingEur: 1500000,
    minFundingRon: 500000,
    source: "Agenția pentru Finanțarea Investițiilor Rurale (AFIR)",
    sourceCategory: "AFIR",
    authorityCode: "AFIR-DR25",
    verifiedStatus: "OFICIAL",
    businessTypes: ["OUAI"],
    industries: ["Irigații & Hidroameliorații", "Cultura Plantelor & Arabil"],
    counties: ["Național"],
    companyAge: "Orice vechime",
    companySize: "Toate mărimile",
    eligibility: [
      "Organizații ale Utilizatorilor de Apă pentru Irigații (OUAI) constituite conform Legii nr. 138/2004.",
      "Preluarea în folosință gratuită a infrastructurii secundare de irigații de la ANIF.",
      "Proiectul demonstrează o economie potențială de apă de minimum 5%–15%.",
    ],
    eligibleExpenses: [
      "Reabilitare stații de pompare a apei pentru irigații (SPA, SPP)",
      "Înlocuire conducte îngropate de aducțiune și distribuție sub presiune",
      "Montare hidranți moderni și contoare electronice de debit",
      "Sisteme de automatizare, telemetrie și senzori SCADA",
    ],
    documents: [
      "Proiect tehnic DALI / Studiu de Fezabilitate avizat ANIF",
      "Protocol de predare-primire a infrastructurii secundare de la ANIF",
      "Aviz de gospodărire a apelor eliberat de ANAR",
    ],
    cofinancing: "0% — Sprijin 100% nerambursabil FEADR.",
    supportIntensity: "100% grant nerambursabil",
    officialUrl: "https://www.afir.ro",
    timeline: [
      { label: "Deschidere sesiune depunere proiecte", date: "15 Iunie 2026" },
      { label: "Termen limită depunere", date: "30 Septembrie 2026" },
      { label: "Contractare proiecte", date: "Noiembrie – Decembrie 2026" },
    ],
    faqs: [
      {
        question: "Cât este contribuția proprie a OUAI-ului?",
        answer: "Contribuția financiară proprie a OUAI-ului este 0%. Proiectul beneficiază de sprijin nerambursabil în procent de 100% din totalul cheltuielilor eligibile.",
      },
    ],
    relatedLegislation: ["regulamentul-ue-2021-2115-pac"],
    relatedNews: ["afir-lansare-apel-dr25-irigatii"],
  },
  {
    slug: "afm-rabla-tractoare-agricultura",
    title: "AFM: Programul Național Rabla pentru Tractoare și Mașini Agricole",
    summary: "Sprijin nerambursabil de până la 20.000 EUR (65%–80% intensitate) pentru fermierii persoane fizice și juridice care casează un tractor sau vehicul uzat și achiziționează un tractor nou.",
    status: "În curând",
    deadline: "2026-10-31",
    maxFundingRon: 100000,
    maxFundingEur: 20000,
    minFundingRon: 25000,
    source: "Administrația Fondului pentru Mediu (AFM)",
    sourceCategory: "AFM",
    authorityCode: "AFM-RABLA-TRAC",
    verifiedStatus: "OFICIAL",
    businessTypes: ["Persoană Fizică", "PFA", "II", "IF", "SRL"],
    industries: ["Utilaje & Mecanizare", "Cultura Plantelor & Arabil", "Tineri Fermieri"],
    counties: ["Național"],
    companyAge: "Orice vechime",
    companySize: "Microîntreprindere",
    eligibility: [
      "Persoane fizice producătoare agricole (deținători atestat de producător) sau PFA/II/SRL agricole.",
      "Predarea spre casare a unui autovehicul uzat sau tractor vechi înregistrat/înmatriculat.",
      "Achiziția unui tractor nou cu normă de poluare Stage V de valoare de până la 55.000 EUR (TVA inclus).",
      "Fără datorii restante la bugetul local și bugetul de stat.",
    ],
    eligibleExpenses: [
      "Achiziție tractor agricol nou",
      "Accesorii agricole atașabile (plug, disc, semănătoare) achiziționate împreună cu tractorul",
    ],
    documents: [
      "Atestat de producător vizat la zi / Certificat de înregistrare ONRC",
      "Certificat atestare fiscală emis de ANAF și primărie",
      "Certificat de radiere / casare emis de colector autorizat REMAT",
    ],
    cofinancing: "20% cofinanțare proprie pentru tineri fermieri sub 40 ani | 35% pentru ceilalți fermieri.",
    supportIntensity: "65% – 80% sprijin nerambursabil",
    officialUrl: "https://www.afm.ro",
    timeline: [
      { label: "Validare dealeri și distribuitori de utilaje", date: "August 2026" },
      { label: "Înscriere fermieri în aplicația informatică AFM", date: "Septembrie – Octombrie 2026" },
    ],
    faqs: [
      {
        question: "Cât este ajutorul maxim acordat de AFM?",
        answer: "Valoarea maximă a sprijinului este de 20.000 EUR (echivalentul a până la 80% din valoarea de achiziție a utilajului pentru tineri fermieri).",
      },
    ],
    relatedNews: ["lansare-program-rabla-tractoare-afm"],
  },
  {
    slug: "start-up-nation-2025",
    title: "Start-Up Nation România — Ediția 2025/2026",
    summary: "Sprijin financiar nerambursabil de până la 250.000 RON pentru înființarea și dezvoltarea de întreprinderi noi prin investiții în echipamente, digitalizare și crearea de noi locuri de muncă.",
    status: "Deschis",
    deadline: "2026-10-15",
    maxFundingRon: 250000,
    maxFundingEur: 50000,
    minFundingRon: 50000,
    source: "Ministerul Economiei, Antreprenoriatului și Turismului (MEAT)",
    sourceCategory: "Minister",
    authorityCode: "MEAT-SUN2025",
    verifiedStatus: "OFICIAL",
    businessTypes: ["SRL"],
    industries: ["IT & Digitalizare", "Procesare Alimentară"],
    counties: ["Național"],
    companyAge: "Nou înființată",
    companySize: "Microîntreprindere",
    eligibility: [
      "Persoana fizică solicitantă trebuie să fi absolvit cursurile de antreprenoriat organizate prin modulul Pilonul I.",
      "Societatea trebuie înființată după absolvirea cursului de către persoana eligibilă.",
      "Sediul social și locul de implementare trebuie să fie pe teritoriul României.",
      "Crearea și menținerea a minimum 2 locuri de muncă cu normă întreagă pe o perioadă de cel puțin 24 luni.",
    ],
    eligibleExpenses: [
      "Echipamente tehnologice, utilaje, calculatoare, softuri",
      "Pachete digitale, site-uri de prezentare, magazine online",
      "Cheltuieli salariale și chirii în limita a 60.000 RON",
    ],
    documents: [
      "Cerere de finanțare completată pe platforma oficială",
      "Plan de afaceri detaliat",
      "Certificat de absolvire curs antreprenoriat",
      "Act constitutiv și Certificat de Înregistrare ONRC",
    ],
    cofinancing: "Minimum 10% cofinanțare proprie din valoarea cheltuielilor eligibile.",
    supportIntensity: "90% grant nerambursabil",
    officialUrl: "https://economie.gov.ro/",
    timeline: [
      { label: "Pilonul I — Cursuri formare", date: "Iunie – August 2026" },
      { label: "Pilonul II — Depunere planuri de afaceri", date: "1 Septembrie – 15 Octombrie 2026" },
      { label: "Evaluare și contractare", date: "Noiembrie 2026 – Ianuarie 2027" },
    ],
    faqs: [
      {
        question: "Cine se poate înscrie în program?",
        answer: "Persoanele fizice din grupul țintă care parcurg cursurile de formare antreprenorială și înființează o firmă nouă de tip SRL.",
      },
    ],
    relatedNews: ["start-up-nation-2025-2026-pilonul-1-2"],
  },
  {
    slug: "pnrr-c9-digitalizare-imm",
    title: "PNRR C9: Digitalizarea IMM-urilor din România",
    summary: "Granturi nerambursabile între 20.000 și 100.000 EUR destinate adoptării tehnologiilor avansate (cloud, securitate cibernetică, automatizări, IoT, ERP) de către IMM-uri non-IT.",
    status: "Deschis",
    deadline: "2026-09-30",
    maxFundingRon: 500000,
    maxFundingEur: 100000,
    minFundingRon: 100000,
    source: "Ministerul Investițiilor și Proiectelor Europene (MIPE)",
    sourceCategory: "PNRR",
    authorityCode: "MIPE-PNRR-C9",
    verifiedStatus: "OFICIAL",
    businessTypes: ["SRL", "SA"],
    industries: ["IT & Digitalizare", "Cultura Plantelor & Arabil", "Procesare Alimentară"],
    counties: ["Național"],
    companyAge: "Peste 1 an",
    companySize: "IMM",
    eligibility: [
      "Persoană juridică înregistrată în România de cel puțin 1 an fiscal încheiat.",
      "Să nu fi înregistrat profit operațional negativ în ultimul exercițiu financiar.",
      "Obligația de a atinge minimum 6 din cele 12 criterii de intensitate digitală DESI la finalul proiectului.",
    ],
    eligibleExpenses: [
      "Servere, calculatoare, echipamente de rețea",
      "Licențe software ERP, CRM, automatizări industriale",
      "Servicii cloud și audit de securitate cibernetică",
    ],
    documents: [
      "Raport de audit de maturitate digitală inițial și final",
      "Situații financiare anuale auditate",
      "Propunere tehnică de implementare hardware/software",
    ],
    cofinancing: "10% cofinanțare privată pentru microîntreprinderi și companii mici.",
    supportIntensity: "90% grant nerambursabil",
    officialUrl: "https://mfe.gov.ro/pnrr/",
    timeline: [
      { label: "Apel deschis pentru depunere", date: "Iulie – Septembrie 2026" },
      { label: "Evaluare și contractare", date: "Octombrie – Decembrie 2026" },
    ],
    faqs: [
      {
        question: "Ce criterii DESI trebuie îndeplinite?",
        answer: "Firma trebuie să bifeze minimum 6 criterii din indicele DESI (de exemplu utilizare ERP, cloud, securitate, comerț electronic, peste 50% angajați cu acces la internet).",
      },
    ],
    relatedNews: ["pnrr-c9-digitalizare-imm-evaluare"],
  },
  {
    slug: "adr-nord-vest-digitalizare-si-inovare",
    title: "ADR Nord-Vest: Inovare și Digitalizare în Microîntreprinderi",
    summary: "Sprijin financiar nerambursabil de până la 70.000 EUR pentru microîntreprinderile din Regiunea Nord-Vest (Cluj, Bihor, Bistrița-Năsăud, Maramureș, Satu Mare, Sălaj).",
    status: "Deschis",
    deadline: "2026-09-30",
    maxFundingRon: 350000,
    maxFundingEur: 70000,
    minFundingRon: 40000,
    source: "Agenția de Dezvoltare Regională Nord-Vest (ADR NV)",
    sourceCategory: "ADR",
    authorityCode: "ADRNV-REGIO-01",
    verifiedStatus: "OFICIAL",
    businessTypes: ["SRL", "PFA"],
    industries: ["IT & Digitalizare", "Procesare Alimentară"],
    counties: ["Cluj", "Bihor", "Bistrița-Năsăud", "Maramureș", "Satu Mare", "Sălaj"],
    companyAge: "Peste 1 an",
    companySize: "Microîntreprindere",
    eligibility: [
      "Microîntreprindere cu sediul social sau punct de lucru înregistrat în Regiunea Nord-Vest.",
      "Număr mediu de salariați de cel puțin 1 în anul anterior depunerii.",
      "Domeniu de activitate menționat în Strategia de Specializare Inteligentă (RIS3 NV).",
    ],
    documents: [
      "Certificat constatator ONRC generat recent",
      "Plan de achiziție echipamente IT și soluții software",
      "Declarație de încadrare în categoria IMM",
    ],
    cofinancing: "15% din valoarea totală a cheltuielilor eligibile.",
    supportIntensity: "85% nerambursabil",
    officialUrl: "https://www.nord-vest.ro/",
    timeline: [
      { label: "Deschidere apel", date: "15 Mai 2026" },
      { label: "Termen limită depunere", date: "30 Septembrie 2026" },
    ],
    faqs: [
      {
        question: "Care sunt județele eligibile?",
        answer: "Județele Cluj, Bihor, Bistrița-Năsăud, Maramureș, Satu Mare și Sălaj.",
      },
    ],
  },
  {
    slug: "adr-centru-microintreprinderi-turism-servicii",
    title: "ADR Centru: Scalarea Microîntreprinderilor din Turism și Servicii",
    summary: "Sprijin nerambursabil de până la 90.000 EUR pentru achiziția de echipamente și modernizarea spațiilor de cazare și alimentație publică din Regiunea Centru.",
    status: "Deschis",
    deadline: "2026-10-31",
    maxFundingRon: 450000,
    maxFundingEur: 90000,
    minFundingRon: 50000,
    source: "Agenția de Dezvoltare Regională Centru (ADR Centru)",
    sourceCategory: "ADR",
    authorityCode: "ADRCENTRU-02",
    verifiedStatus: "OFICIAL",
    businessTypes: ["SRL", "PFA"],
    industries: ["Procesare Alimentară", "Energie Verde & Mediu"],
    counties: ["Alba", "Brașov", "Covasna", "Harghita", "Mureș", "Sibiu"],
    companyAge: "Peste 2 ani",
    companySize: "Microîntreprindere",
    eligibility: [
      "Sediul social sau punct de lucru funcțional în județele Alba, Brașov, Covasna, Harghita, Mureș sau Sibiu.",
      "Minimum 1 angajat cu normă întreagă în ultimul an fiscal.",
      "Proiectul contribuie la crearea a cel puțin un loc de muncă sustenabil.",
    ],
    documents: [
      "Certificat de clasificare structură turistică (unde este cazul)",
      "Situații financiare 2024 și 2025",
      "Plan de investiții și oferte ferme",
    ],
    cofinancing: "10% din cheltuielile eligibile.",
    supportIntensity: "90% nerambursabil",
    officialUrl: "https://www.regio-adrcentru.ro/",
    timeline: [
      { label: "Lansare apel", date: "1 Iunie 2026" },
      { label: "Termen limită", date: "31 Octombrie 2026" },
    ],
    faqs: [
      {
        question: "Se pot finanța lucrări de renovare?",
        answer: "Da, în limita a 40% din bugetul eligibil al proiectului.",
      },
    ],
  },
];

export function formatCurrencyRon(value: number): string {
  return new Intl.NumberFormat("ro-RO", {
    style: "currency",
    currency: "RON",
    maximumFractionDigits: 0,
  }).format(value);
}

export function formatCurrencyEur(value: number): string {
  return new Intl.NumberFormat("ro-RO", {
    style: "currency",
    currency: "EUR",
    maximumFractionDigits: 0,
  }).format(value);
}

export function calculateDaysRemaining(deadlineStr: string): number {
  const deadlineDate = new Date(`${deadlineStr}T23:59:59`);
  const diffTime = deadlineDate.getTime() - Date.now();
  return Math.max(0, Math.ceil(diffTime / (1000 * 60 * 60 * 24)));
}
