export type PublicInstitutionType = 
  | "Minister"
  | "Agenție Națională"
  | "Autoritate de Reglementare"
  | "Bancă Centrală"
  | "Agenție de Finanțare"
  | "Instituție Europeană";

export type GovernmentEntity = {
  id: string;
  name: string;
  acronym: string;
  type: PublicInstitutionType;
  role: string;
  domain: string;
  officialWebsite: string;
  portalUrl?: string;
  subordinateAgencies: string[];
  keyPrograms: string[];
  legislationContext: string;
  address: string;
  contactEmail: string;
  lastVerifiedAt: string;
};

export const ROMANIAN_GOVERNMENT_MINISTRIES: GovernmentEntity[] = [
  {
    id: "madr",
    name: "Ministerul Agriculturii și Dezvoltării Rurale",
    acronym: "MADR",
    type: "Minister",
    role: "Elaborează și implementează politicile agricole naționale, Planul Strategic PAC 2023-2027, schemele de ajutor de stat în agricultură și industria alimentară.",
    domain: "Agricultură, Dezvoltare Rurală, Industrie Alimentară, Pescuit",
    officialWebsite: "https://www.madr.ro",
    subordinateAgencies: ["APIA", "AFIR", "ANIF", "ANZ", "ANPA", "ICDF"],
    keyPrograms: ["InvestAlim", "Creditul Fermierului", "Subvenții motorină agricolă", "Sprijin cuplat în agricultură"],
    legislationContext: "Ordonanța de Urgență a Guvernului nr. 195/2005, Legea 37/2015, HG 1570/2022",
    address: "B-dul Carol I nr. 2-4, Sector 3, București",
    contactEmail: "relatii.publice@madr.ro",
    lastVerifiedAt: "2026-10-01",
  },
  {
    id: "mfe",
    name: "Ministerul Investițiilor și Proiectelor Europene",
    acronym: "MIPE",
    type: "Minister",
    role: "Autoritate de Management Națională responsabilă de coordonarea fondurilor europene structurale și de investiții (FEDR, FSE+, FC, FTJ) și gestionarea PNRR.",
    domain: "Fonduri Europene, Programe Regionale, Tranziție Justă, Digitalizare",
    officialWebsite: "https://mfe.gov.ro",
    portalUrl: "https://mysmis2020.gov.ro",
    subordinateAgencies: ["Autoritățile de Management pentru Programe Naționale (PoCIDIF, PDD, PEO, PS, PTJ)"],
    keyPrograms: ["PoCIDIF (Digitalizare IMM)", "Programul Tranziție Justă (PTJ)", "Programul Dezvoltare Durabilă (PDD)", "Programul Sănătate (PS)"],
    legislationContext: "OUG 133/2021, OUG 23/2023 privind gestionarea fondurilor externe nerambursabile",
    address: "Șos. București-Ploiești nr. 1-1B, Clădirea Victoria Office, Sector 1, București",
    contactEmail: "cabinet.ministru@mfe.gov.ro",
    lastVerifiedAt: "2026-10-01",
  },
  {
    id: "meat",
    name: "Ministerul Economiei, Antreprenoriatului și Turismului",
    acronym: "MEAT",
    type: "Minister",
    role: "Gestionează politicile industriale, programele naționale de susținere a antreprenoriatului, IMM-urilor, dezvoltarea comerțului exterior și a sectorului turistic.",
    domain: "Economie, IMM, Start-up, Turism, Industrie, Comerț",
    officialWebsite: "https://economie.gov.ro",
    subordinateAgencies: ["Agențiile Teritoriale pentru IMM, Atragere de Investiții și Promovare a Exportului (AIMMAIPE)"],
    keyPrograms: ["Start-Up Nation România", "Femeia Antreprenor", "Programul de Microindustrializare", "Programul Comerț și Servicii", "ConstructPlus"],
    legislationContext: "Legea nr. 346/2004 privind stimularea înființării și dezvoltării IMM-urilor",
    address: "Calea Victoriei nr. 152, Sector 1, București",
    contactEmail: "presa@economie.gov.ro",
    lastVerifiedAt: "2026-10-01",
  },
  {
    id: "energie",
    name: "Ministerul Energiei",
    acronym: "ME",
    type: "Minister",
    role: "Coordonează strategia energetică a României, dezvoltarea capacităților de producție regenerabilă, rețelele de transport și Fondul pentru Modernizare.",
    domain: "Energie Electrică, Gaze Naturale, Regenerabile, Stocare BESS, Decarbonizare",
    officialWebsite: "https://energie.gov.ro",
    subordinateAgencies: ["Transelectrica (monitorizată)", "Transgaz", "Dispeceratul Energetic Național"],
    keyPrograms: ["Fondul pentru Modernizare (Autoconsum & Producție)", "PNRR Componenta 6 Energie", "Schema de sprijin pentru Contracte pentru Diferență (CfD)"],
    legislationContext: "Legea Energiei Electrice și a Gazelor Naturale nr. 123/2012, OUG 112/2022",
    address: "Str. Academiei nr. 39-41, Sector 1, București",
    contactEmail: "comunicare@energie.gov.ro",
    lastVerifiedAt: "2026-10-01",
  },
  {
    id: "mediu",
    name: "Ministerul Mediului, Apelor și Pădurilor",
    acronym: "MMAP",
    type: "Minister",
    role: "Reglementează protecția mediului, gestionarea resurselor de apă, gospodărirea pădurilor și coordonează Administrația Fondului pentru Mediu.",
    domain: "Mediu, Economie Circulară, Păduri, Ape, Biodiversitate",
    officialWebsite: "https://www.mmediu.ro",
    subordinateAgencies: ["AFM (Administrația Fondului pentru Mediu)", "ANPM", "Garda Națională de Mediu", "Apele Române"],
    keyPrograms: ["Casa Verde Fotovoltaice", "Rabla Clasic & Rabla Plus", "Rabla pentru Tractoare", "Programul de Reciclare a Deșeurilor"],
    legislationContext: "OUG 195/2005 privind protecția mediului, OUG 92/2021 privind regimul deșeurilor",
    address: "B-dul Libertății nr. 12, Sector 5, București",
    contactEmail: "comunicare@mmediu.ro",
    lastVerifiedAt: "2026-10-01",
  },
  {
    id: "finante",
    name: "Ministerul Finanțelor",
    acronym: "MF",
    type: "Minister",
    role: "Elaborează politica fiscal-bugetară, legislația privind impozitarea companiilor, TVA, schemele mari de ajutor de stat pentru investiții regionale și coordonează ANAF.",
    domain: "Finanțe Publice, Fiscalitate, Buget, Ajutor de Stat, Trezorerie",
    officialWebsite: "https://mfinante.gov.ro",
    subordinateAgencies: ["ANAF (Agenția Națională de Administrare Fiscală)", "Autoritatea Vamală Română", "ONJN"],
    keyPrograms: ["Schema de Ajutor de Stat HG 807/2014 (Mari Investiții)", "Schema HG 959/2022 (Industrii Prelucrătoare)", "Garanții IMM Invest Plus"],
    legislationContext: "Legea nr. 227/2015 privind Codul Fiscal, Legea nr. 207/2015 privind Codul de Procedură Fiscală",
    address: "B-dul Libertății nr. 16, Sector 5, București",
    contactEmail: "publicinfo@mfinante.gov.ro",
    lastVerifiedAt: "2026-10-01",
  },
  {
    id: "dezvoltare",
    name: "Ministerul Dezvoltării, Lucrărilor Publice și Administrației",
    acronym: "MDLPA",
    type: "Minister",
    role: "Coordonează politicile de dezvoltare teritorială, construcții, urbanism, reabilitare energetică a clădirilor și Programul Național de Investiții Anghel Saligny.",
    domain: "Dezvoltare Teritorială, Construcții, Urbanism, Infrastructură Locală",
    officialWebsite: "https://www.mdlpa.ro",
    subordinateAgencies: ["Compania Națională de Investiții (CNI)", "Inspectoratul de Stat în Construcții (ISC)", "ANL"],
    keyPrograms: ["Programul Național Anghel Saligny", "Programul Național de Consolidare a Clădirilor cu Risc Seismic", "Valul Renovării (PNRR C5)"],
    legislationContext: "Legea nr. 50/1991 privind autorizarea executării lucrărilor de construcții, OUG 95/2021",
    address: "B-dul Libertății nr. 16, Latura Nord, Sector 5, București",
    contactEmail: "info@mdlpa.ro",
    lastVerifiedAt: "2026-10-01",
  },
  {
    id: "munca",
    name: "Ministerul Muncii și Solidarității Sociale",
    acronym: "MMSS",
    type: "Minister",
    role: "Reglementează piața muncii, relațiile de muncă, securitatea socială, formarea profesională și politicile de ocupare.",
    domain: "Piața Muncii, Ocupare, Calificare, Asistență Socială, Pensii",
    officialWebsite: "https://mmuncii.ro",
    subordinateAgencies: ["ANOFM (Agenția Națională pentru Ocuparea Forței de Muncă)", "Inspecția Muncii", "ANPIS"],
    keyPrograms: ["Subvenții pentru angajarea tinerilor NEETs și șomerilor (Legea 76/2002)", "Programul Educație și Ocupare (PEO 2021-2027)"],
    legislationContext: "Legea nr. 53/2003 - Codul Muncii, Legea nr. 76/2002 privind sistemul asigurărilor pentru șomaj",
    address: "Str. Dem. I. Dobrescu nr. 2-4, Sector 1, București",
    contactEmail: "presa@mmuncii.ro",
    lastVerifiedAt: "2026-10-01",
  },
  {
    id: "transporturi",
    name: "Ministerul Transporturilor și Infrastructurii",
    acronym: "MTI",
    type: "Minister",
    role: "Planifică și finanțează dezvoltarea infrastructurii rutiere majore (autostrăzi, drumuri expres), feroviare (TEN-T), aeriene și portuare.",
    domain: "Transport Rutier, Feroviar, Aerian, Naval, Infrastructură Mare",
    officialWebsite: "https://www.mt.ro",
    subordinateAgencies: ["CNAIR", "CNIR", "CFR SA", "CFR Călători", "Autoritatea Aeronautică Civilă Română", "Administrația Porturilor Maritime Constanța"],
    keyPrograms: ["Programul Transport (PT 2021-2027)", "Master Planul General de Transport al României", "Investiții Autostrada Moldovei A7, A8, A3"],
    legislationContext: "OUG 55/2016 privind reorganizarea CNAIR, Legea 37/2021",
    address: "B-dul Dinicu Golescu nr. 38, Sector 1, București",
    contactEmail: "presa.mti@mt.ro",
    lastVerifiedAt: "2026-10-01",
  },
  {
    id: "cercetare",
    name: "Ministerul Cercetării, Inovării și Digitalizării",
    acronym: "MCID",
    type: "Minister",
    role: "Coordonează strategia națională de cercetare-dezvoltare-inovare (CDI), transformarea digitală a administrației și cloud-ul guvernamental.",
    domain: "Cercetare, Inovare, Digitalizare, Cloud Guvernamental, AI",
    officialWebsite: "https://www.mcid.gov.ro",
    subordinateAgencies: ["ADR (Autoritatea pentru Digitalizarea României)", "UEFISCDI", "DNSC (Directoratul Național de Securitate Cibernetică)"],
    keyPrograms: ["Planul Național de Cercetare-Dezvoltare și Inovare (PNCDI IV)", "Cloud-ul Dedicat Guvernamental", "Horizon Europe Partnering"],
    legislationContext: "Legea nr. 25/2023 privind interoperabilitatea, OUG 89/2022 privind cloud-ul guvernamental",
    address: "Str. Mendeleev nr. 21-25, Sector 1, București",
    contactEmail: "comunicare@mcid.gov.ro",
    lastVerifiedAt: "2026-10-01",
  },
];

export const ROMANIAN_NATIONAL_AGENCIES: GovernmentEntity[] = [
  {
    id: "ancpi",
    name: "Agenția Națională de Cadastru și Publicitate Imobiliară",
    acronym: "ANCPI",
    type: "Agenție Națională",
    role: "Administrează sistemul integrat de cadastru și carte funciară (e-Terra), înregistrarea actelor de transfer al proprietății și Programul Național de Cadastru și Carte Funciară (PNCCF).",
    domain: "Cadastru, Carte Funciară, Tranzacții Imobiliare, Intabulare",
    officialWebsite: "https://www.ancpi.ro",
    portalUrl: "https://epay.ancpi.ro",
    subordinateAgencies: ["42 de Oficii de Cadastru și Publicitate Imobiliară (OCPI Județene)"],
    keyPrograms: ["Programul Național de Cadastru și Carte Funciară (PNCCF)", "Sistemul informatic e-Terra"],
    legislationContext: "Legea Cadastrului și a Publicității Imobiliare nr. 7/1996 republicată",
    address: "Splaiul Independenței nr. 202A, Sector 6, București",
    contactEmail: "relatiicupublicul@ancpi.ro",
    lastVerifiedAt: "2026-10-01",
  },
  {
    id: "anaf",
    name: "Agenția Națională de Administrare Fiscală",
    acronym: "ANAF",
    type: "Agenție Națională",
    role: "Asigură colectarea impozitelor, taxelor și contribuțiilor la bugetul general consolidat, administrează Spațiul Privat Virtual (SPV), RO e-Factura, RO e-Transport și SAF-T.",
    domain: "Administrare Fiscală, Impozite, RO e-Factura, SPV, SAF-T",
    officialWebsite: "https://www.anaf.ro",
    portalUrl: "https://pfinternet.anaf.ro",
    subordinateAgencies: ["Direcțiile Generale Regionale ale Finanțelor Publice (DGRFP)"],
    keyPrograms: ["Sistemul RO e-Factura B2B/B2G", "RO e-Transport", "Declarația Unică", "SAF-T (D406)"],
    legislationContext: "Codul Fiscal (Legea 227/2015), Codul de Procedură Fiscală (Legea 207/2015)",
    address: "Str. Apolodor nr. 17, Sector 5, București",
    contactEmail: "presa@anaf.ro",
    lastVerifiedAt: "2026-10-01",
  },
  {
    id: "onrc",
    name: "Oficiul Național al Registrului Comerțului",
    acronym: "ONRC",
    type: "Agenție Națională",
    role: "Ține registrul comerțului, efectuează înmatriculările de societăți (SRL, SA), persoane fizice autorizate (PFA), întreprinderi individuale (II) și eliberează certificate constatatoare.",
    domain: "Registrul Comerțului, Înființare Firme, Coduri CAEN, Insolvență",
    officialWebsite: "https://www.onrc.ro",
    portalUrl: "https://myportal.onrc.ro",
    subordinateAgencies: ["Oficiile Registrului Comerțului de pe lângă Tribunalele Județene"],
    keyPrograms: ["Portalul Integrat de Servicii Online ONRC", "Buletinul Procedurilor de Insolvență (BPI)"],
    legislationContext: "Legea nr. 265/2022 privind registrul comerțului",
    address: "B-dul Unirii nr. 74, Sector 3, București",
    contactEmail: "onrc@onrc.ro",
    lastVerifiedAt: "2026-10-01",
  },
  {
    id: "insse",
    name: "Institutul Național de Statistică",
    acronym: "INSSE",
    type: "Agenție Națională",
    role: "Organul oficial de stat responsabil de colectarea, prelucrarea și diseminarea statisticilor oficiale privind economia, demografia, prețurile, comerțul exterior și agricultura României.",
    domain: "Statistici Naționale, PIB, Inflație IPC, Comerț Exterior, Demografie",
    officialWebsite: "https://insse.ro",
    portalUrl: "http://statistici.insse.ro:8077/tempo-online/",
    subordinateAgencies: ["Direcțiile Județene de Statistică (DJS)"],
    keyPrograms: ["Baza de date TEMPO-Online", "Recensământul General Agricol", "Buletine Statistice Lunare"],
    legislationContext: "Legea nr. 226/2009 privind organizarea și funcționarea statisticii oficiale în România",
    address: "B-dul Libertății nr. 16, Sector 5, București",
    contactEmail: "insse@insse.ro",
    lastVerifiedAt: "2026-10-01",
  },
  {
    id: "bnr",
    name: "Banca Națională a României",
    acronym: "BNR",
    type: "Bancă Centrală",
    role: "Banca centrală a României responsabilă de politica monetară, stabilitatea prețurilor, reglementarea bancară, calcularea indicilor IRCC și ROBOR și raportarea balanței de plăți.",
    domain: "Politică Monetară, IRCC, ROBOR, Curs Valutar, Rezerve Valutare",
    officialWebsite: "https://www.bnr.ro",
    subordinateAgencies: ["Sucursalele Regionale BNR"],
    keyPrograms: ["Raportul trimestrial asupra inflației", "Indicele de referință IRCC (OUG 19/2019)", "Statistica Investițiilor Străine Directe (ISD)"],
    legislationContext: "Legea nr. 312/2004 privind Statutul Băncii Naționale a României",
    address: "Str. Lipscani nr. 25, Sector 3, București",
    contactEmail: "info@bnro.ro",
    lastVerifiedAt: "2026-10-01",
  },
  {
    id: "anre",
    name: "Autoritatea Națională de Reglementare în Domeniul Energiei",
    acronym: "ANRE",
    type: "Autoritate de Reglementare",
    role: "Reglementează piețele de energie electrică și gaze naturale, licențierea operatorilor, regulile pentru prosumatori și tarifele de rețea.",
    domain: "Reglementare Energie, Prosumatori, Certificate Verzi, Licențe",
    officialWebsite: "https://www.anre.ro",
    subordinateAgencies: [],
    keyPrograms: ["Portalul de Schimbare a Furnizorului (POSF)", "Registrul Prosumatorilor de Energie"],
    legislationContext: "OUG 33/2007 privind organizarea și funcționarea ANRE",
    address: "Str. Constantin Nacu nr. 3, Sector 2, București",
    contactEmail: "anre@anre.ro",
    lastVerifiedAt: "2026-10-01",
  },
  {
    id: "concurenta",
    name: "Consiliul Concurenței",
    acronym: "CC",
    type: "Autoritate de Reglementare",
    role: "Protejează și stimulează concurența pe piețele din România, investighează abuzurile de poziție dominantă, cartelurile și avizează schemele naționale de ajutor de stat.",
    domain: "Concurență, Ajutor de Stat, Monitorul Prețurilor, Concentrări Economice",
    officialWebsite: "https://www.consiliulconcurentei.ro",
    portalUrl: "https://www.monitorulpreturilor.info",
    subordinateAgencies: ["Inspectoratele Teritoriale de Concurență"],
    keyPrograms: ["Registrul Ajutoarelor de Stat (RegAS)", "Monitorul Prețurilor la Alimente și Carburanți"],
    legislationContext: "Legea Concurenței nr. 21/1996 republicată, OUG 77/2014 privind ajutorul de stat",
    address: "Piața Presei Libere nr. 1, Corp D1, Sector 1, București",
    contactEmail: "contact@consiliulconcurentei.ro",
    lastVerifiedAt: "2026-10-01",
  },
  {
    id: "anofm",
    name: "Agenția Națională pentru Ocuparea Forței de Muncă",
    acronym: "ANOFM",
    type: "Agenție Națională",
    role: "Implementează măsurile active de ocupare, organizează bursele locurilor de muncă, acordă subvenții angajatorilor și gestionează asigurările pentru șomaj.",
    domain: "Ocupare Forță de Muncă, Subvenții Angajatori, Formare Profesională, Șomaj",
    officialWebsite: "https://www.anofm.ro",
    subordinateAgencies: ["41 de Agenții Județene pentru Ocuparea Forței de Muncă (AJOFM) + AMOFM București"],
    keyPrograms: ["Subvenții art. 80 și art. 85 din Legea 76/2002 (Absolvenți, Șomeri >45 ani, Persoane cu dizabilități)", "Prime de încadrare și mobilitate"],
    legislationContext: "Legea nr. 76/2002 privind sistemul asigurărilor pentru șomaj",
    address: "Str. Avalanșei nr. 20-22, Sector 4, București",
    contactEmail: "anofm@anofm.gov.ro",
    lastVerifiedAt: "2026-10-01",
  },
  {
    id: "anap",
    name: "Agenția Națională pentru Achiziții Publice",
    acronym: "ANAP",
    type: "Autoritate de Reglementare",
    role: "Reglementează cadrul achizițiilor publice din România, asigură verificarea documentațiilor de atribuire și monitorizează funcționarea sistemului electronic SEAP / SICAP.",
    domain: "Achiziții Publice, SEAP/SICAP, Licitații, Legislație Achiziții",
    officialWebsite: "https://anap.gov.ro",
    portalUrl: "https://www.e-licitatie.ro",
    subordinateAgencies: [],
    keyPrograms: ["Sistemul Informatic Colaborativ pentru Achiziții Publice (SICAP/SEAP)", "Ghidul Național de Achiziții Publice"],
    legislationContext: "Legea nr. 98/2016 privind achizițiile publice, Legea nr. 99/2016 privind achizițiile sectoriale",
    address: "Str. Foișorului nr. 2, Sector 3, București",
    contactEmail: "contact@anap.gov.ro",
    lastVerifiedAt: "2026-10-01",
  },
];
