export type DownloadResource = {
  id: string;
  slug: string;
  title: string;
  description: string;
  category: "Ghid Solicitant" | "Formular APIA" | "Model Plan de Afaceri" | "Declarație Tip" | "Contract Model" | "Ghid Tehnic" | "Instrument Financiar";
  institution: "APIA" | "AFIR" | "MADR" | "AFM" | "MEAT" | "MIPE" | "SUBVENȚII";
  fileFormat: "PDF" | "DOCX" | "XLSX" | "Portal Oficial";
  fileSizeMb?: number;
  documentDate?: string;
  downloadUrl: string;
  officialSource: string;
  verifiedAt?: string;
  isExternalPortal?: boolean;
  disclaimer?: string;
};

export const downloadableResourcesCatalog: DownloadResource[] = [
  {
    id: "res-afir-dr14",
    slug: "ghid-solicitant-dr14-ferme-mici",
    title: "Ghidul Solicitantului & Anexe AFIR DR-14 — Ferme de Mici Dimensiuni",
    description: "Documentația oficială aprobată de MADR/AFIR pentru accesarea sprijinului de până la 50.000 EUR (intensitate 85%), conținând condițiile de eligibilitate, anexa de plan de afaceri și grila de punctaj.",
    category: "Ghid Solicitant",
    institution: "AFIR",
    fileFormat: "Portal Oficial",
    documentDate: "August 2026",
    downloadUrl: "https://www.afir.ro/domenii-de-interventie/detalii-si-anexe-dr-14",
    officialSource: "https://www.afir.ro/domenii-de-interventie/detalii-si-anexe-dr-14",
    verifiedAt: "13 Septembrie 2026, 23:08",
    isExternalPortal: true,
  },
  {
    id: "res-afir-dr30",
    slug: "ghid-solicitant-dr30-tineri-fermieri",
    title: "Ghidul Solicitantului & Anexe AFIR DR-30 — Instalarea Tinerilor Fermieri",
    description: "Pachetul complet de documente oficiale AFIR pentru grantul forfetar de 70.000 EUR: instrucțiuni de completare a cererii online, model de plan de afaceri și lista documentelor obligatorii.",
    category: "Ghid Solicitant",
    institution: "AFIR",
    fileFormat: "Portal Oficial",
    documentDate: "August 2026",
    downloadUrl: "https://www.afir.ro/domenii-de-interventie/detalii-si-anexe-dr-30",
    officialSource: "https://www.afir.ro/domenii-de-interventie/detalii-si-anexe-dr-30",
    verifiedAt: "13 Septembrie 2026, 23:08",
    isExternalPortal: true,
  },
  {
    id: "res-afir-dr25",
    slug: "ghid-solicitant-dr25-irigatii-ouai",
    title: "Ghidul Solicitantului & Anexe AFIR DR-25 — Modernizare Irigații OUAI",
    description: "Ghidul oficial și anexele tehnice pentru finanțarea 100% nerambursabilă de până la 1.500.000 EUR per organizație a utilizatorilor de apă pentru irigații (OUAI/FOUAI).",
    category: "Ghid Solicitant",
    institution: "AFIR",
    fileFormat: "Portal Oficial",
    documentDate: "Iunie 2026",
    downloadUrl: "https://www.afir.ro/domenii-de-interventie/detalii-si-anexe-dr-25",
    officialSource: "https://www.afir.ro/domenii-de-interventie/detalii-si-anexe-dr-25",
    verifiedAt: "13 Septembrie 2026, 23:08",
    isExternalPortal: true,
  },
  {
    id: "res-afir-dr15",
    slug: "ghid-solicitant-dr15-exploatatii-vegetale",
    title: "Ghidul Solicitantului & Anexe AFIR DR-15 — Exploatații Sector Vegetal",
    description: "Documentația oficială completă pentru investiții mari în sectorul vegetal (silozuri, depozite, utilaje mari de până la 1.500.000 – 3.000.000 EUR).",
    category: "Ghid Solicitant",
    institution: "AFIR",
    fileFormat: "Portal Oficial",
    documentDate: "Iulie 2026",
    downloadUrl: "https://www.afir.ro/domenii-de-interventie/detalii-si-anexe-dr-15",
    officialSource: "https://www.afir.ro/domenii-de-interventie/detalii-si-anexe-dr-15",
    verifiedAt: "13 Septembrie 2026, 23:08",
    isExternalPortal: true,
  },
  {
    id: "res-apia-1",
    slug: "ghid-solicitant-plati-directe-apia-2026",
    title: "Materiale de Informare & Ghiduri Oficiale APIA — Plăți Directe",
    description: "Materialele oficiale de informare și ghidurile publicate de Agenția de Plăți și Intervenție pentru Agricultură privind schemele de plăți directe, eco-schemele și depunerea cererilor.",
    category: "Ghid Solicitant",
    institution: "APIA",
    fileFormat: "Portal Oficial",
    documentDate: "Campania 2026",
    downloadUrl: "https://apia.org.ro/materiale-de-informare/",
    officialSource: "https://apia.org.ro/materiale-de-informare/",
    verifiedAt: "13 Septembrie 2026, 23:12",
    isExternalPortal: true,
  },
  {
    id: "res-apia-2",
    slug: "formulare-cereri-declaratii-apia",
    title: "Formulare, Cereri & Declarații Oficiale APIA",
    description: "Secțiunea oficială APIA de formulare și cereri descărcabile (formularele M1, M2, M3 de modificare/retragere declarații de suprafață, sector zootehnic și cereri de acord).",
    category: "Formular APIA",
    institution: "APIA",
    fileFormat: "Portal Oficial",
    documentDate: "Campania 2026",
    downloadUrl: "https://apia.org.ro/formulare1386829353/",
    officialSource: "https://apia.org.ro/formulare1386829353/",
    verifiedAt: "13 Septembrie 2026, 23:12",
    isExternalPortal: true,
  },
  {
    id: "res-madr-1",
    slug: "documente-implementare-ps-pac-madr",
    title: "Documente Oficiale de Implementare PS-PAC 2023–2027 — MADR",
    description: "Cadrul de reglementare, manualele de proceduri și deciziile oficiale emise de Ministerul Agriculturii și Dezvoltării Rurale pentru implementarea măsurilor din Planul Strategic PAC.",
    category: "Ghid Solicitant",
    institution: "MADR",
    fileFormat: "Portal Oficial",
    documentDate: "2026",
    downloadUrl: "https://www.madr.ro/planul-national-strategic-pac-post-2020/implementare-ps-pac-2023-2027/documente-implementare-ps-pac.html",
    officialSource: "https://www.madr.ro/planul-national-strategic-pac-post-2020/implementare-ps-pac-2023-2027/documente-implementare-ps-pac.html",
    verifiedAt: "13 Septembrie 2026, 23:12",
    isExternalPortal: true,
  },
  {
    id: "res-afm-1",
    slug: "ghid-rabla-tractoare-afm-instructiuni",
    title: "Ghid de Finanțare & Instrucțiuni Oficiale AFM — Rabla pentru Tractoare",
    description: "Pagina oficială a Administrației Fondului pentru Mediu (AFM) cuprinzând ghidul de finanțare, dispozițiile de deschidere a sesiunii și instrucțiunile pentru fermieri și dealeri validați.",
    category: "Ghid Solicitant",
    institution: "AFM",
    fileFormat: "Portal Oficial",
    documentDate: "2026",
    downloadUrl: "https://www.afm.ro/rabla_tractoare_ghid_finantare.php",
    officialSource: "https://www.afm.ro/rabla_tractoare_ghid_finantare.php",
    verifiedAt: "13 Septembrie 2026, 23:12",
    isExternalPortal: true,
  },
  {
    id: "res-subventii-xlsx",
    slug: "calculator-buget-investitie-agricola-xlsx",
    title: "Machetă Excel Calcul Buget & Cashflow Fermă Agricolă (Instrument SUBVENȚII)",
    description: "Fișier automatizat cu formule matematice reale (VAN/NPV la 8%, RIR/IRR, perioadă de recuperare, P&L, EBITDA, cashflow pe 5 ani și 3 scenarii de rentabilitate).",
    category: "Instrument Financiar",
    institution: "SUBVENȚII",
    fileFormat: "XLSX",
    fileSizeMb: 0.01,
    documentDate: "13 Septembrie 2026",
    downloadUrl: "/resources/macheta_buget_ferma.xlsx",
    officialSource: "Instrument financiar SUBVENȚII — model orientativ de lucru. Nu este formular oficial AFIR.",
    verifiedAt: "13 Septembrie 2026, 23:08",
    isExternalPortal: false,
    disclaimer: "Material de lucru orientativ. Nu este formular oficial AFIR și nu înlocuiește documentele sau cerințele ghidului solicitantului.",
  },
  {
    id: "res-subventii-pa",
    slug: "model-orientativ-plan-afaceri-ferma-docx",
    title: "Model Orientativ SUBVENȚII — Structură Plan de Afaceri Fermă (DOCX)",
    description: "Format editabil de lucru cuprinzând capitolele esențiale necesare structurării unui proiect agricol (situație existentă, obiective, plan operațional, investiții și indicatori de rezultat).",
    category: "Model Plan de Afaceri",
    institution: "SUBVENȚII",
    fileFormat: "DOCX",
    fileSizeMb: 0.04,
    documentDate: "13 Septembrie 2026",
    downloadUrl: "/resources/model_orientativ_plan_afaceri_ferma.docx",
    officialSource: "Material orientativ SUBVENȚII. Nu este formular oficial AFIR și nu înlocuiește ghidul solicitantului.",
    verifiedAt: "13 Septembrie 2026, 23:08",
    isExternalPortal: false,
    disclaimer: "Material de lucru orientativ. Nu este formular oficial AFIR și nu înlocuiește cerințele ghidului solicitantului.",
  },
  {
    id: "res-subventii-ca",
    slug: "model-orientativ-contract-arendare-docx",
    title: "Model Orientativ SUBVENȚII — Contract de Arendare Teren Agricol (DOCX)",
    description: "Șablon cadru orientativ întocmit în conformitate cu prevederile Codului Civil (art. 1836–1850). Nu este formular oficial MADR și trebuie verificat juridic înainte de utilizare.",
    category: "Contract Model",
    institution: "SUBVENȚII",
    fileFormat: "DOCX",
    fileSizeMb: 0.04,
    documentDate: "13 Septembrie 2026",
    downloadUrl: "/resources/model_orientativ_contract_arendare.docx",
    officialSource: "Model orientativ conform Codului Civil. Nu este formular oficial MADR și trebuie verificat juridic.",
    verifiedAt: "13 Septembrie 2026, 23:08",
    isExternalPortal: false,
    disclaimer: "Model orientativ conform Codului Civil. Nu este formular oficial MADR și trebuie verificat juridic înainte de semnare.",
  },
];
